apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: api-gateway
  namespace: default
spec:
  selector:
    matchLabels:
      app: api-gateway
  rules:
    - from:
        - source:
            namespaces: ["istio-system"]
      to:
        - operation:
            ports: ["8080"]
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: auth-service
  namespace: default
spec:
  selector:
    matchLabels:
      app: auth-service
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/default/sa/api-gateway-sa
      to:
        - operation:
            ports: ["50051"]
