// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: auth.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthService_SubmitEmail_FullMethodName           = "/auth.AuthService/SubmitEmail"
	AuthService_VerifyEmailCode_FullMethodName       = "/auth.AuthService/VerifyEmailCode"
	AuthService_PasskeyRegisterBegin_FullMethodName  = "/auth.AuthService/PasskeyRegisterBegin"
	AuthService_PasskeyRegisterFinish_FullMethodName = "/auth.AuthService/PasskeyRegisterFinish"
	AuthService_PasskeyLoginBegin_FullMethodName     = "/auth.AuthService/PasskeyLoginBegin"
	AuthService_PasskeyLoginFinish_FullMethodName    = "/auth.AuthService/PasskeyLoginFinish"
	AuthService_RefreshToken_FullMethodName          = "/auth.AuthService/RefreshToken"
	AuthService_Logout_FullMethodName                = "/auth.AuthService/Logout"
)

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthServiceClient interface {
	SubmitEmail(ctx context.Context, in *SubmitEmailRequest, opts ...grpc.CallOption) (*SubmitEmailResponse, error)
	VerifyEmailCode(ctx context.Context, in *VerifyEmailCodeRequest, opts ...grpc.CallOption) (*VerifyEmailCodeResponse, error)
	PasskeyRegisterBegin(ctx context.Context, in *PasskeyRegisterBeginRequest, opts ...grpc.CallOption) (*PasskeyRegisterBeginResponse, error)
	PasskeyRegisterFinish(ctx context.Context, in *PasskeyRegisterFinishRequest, opts ...grpc.CallOption) (*PasskeyRegisterFinishResponse, error)
	PasskeyLoginBegin(ctx context.Context, in *PasskeyLoginBeginRequest, opts ...grpc.CallOption) (*PasskeyLoginBeginResponse, error)
	PasskeyLoginFinish(ctx context.Context, in *PasskeyLoginFinishRequest, opts ...grpc.CallOption) (*PasskeyLoginFinishResponse, error)
	RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*RefreshTokenResponse, error)
	Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error)
}

type authServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceClient(cc grpc.ClientConnInterface) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) SubmitEmail(ctx context.Context, in *SubmitEmailRequest, opts ...grpc.CallOption) (*SubmitEmailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitEmailResponse)
	err := c.cc.Invoke(ctx, AuthService_SubmitEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) VerifyEmailCode(ctx context.Context, in *VerifyEmailCodeRequest, opts ...grpc.CallOption) (*VerifyEmailCodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyEmailCodeResponse)
	err := c.cc.Invoke(ctx, AuthService_VerifyEmailCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) PasskeyRegisterBegin(ctx context.Context, in *PasskeyRegisterBeginRequest, opts ...grpc.CallOption) (*PasskeyRegisterBeginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PasskeyRegisterBeginResponse)
	err := c.cc.Invoke(ctx, AuthService_PasskeyRegisterBegin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) PasskeyRegisterFinish(ctx context.Context, in *PasskeyRegisterFinishRequest, opts ...grpc.CallOption) (*PasskeyRegisterFinishResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PasskeyRegisterFinishResponse)
	err := c.cc.Invoke(ctx, AuthService_PasskeyRegisterFinish_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) PasskeyLoginBegin(ctx context.Context, in *PasskeyLoginBeginRequest, opts ...grpc.CallOption) (*PasskeyLoginBeginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PasskeyLoginBeginResponse)
	err := c.cc.Invoke(ctx, AuthService_PasskeyLoginBegin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) PasskeyLoginFinish(ctx context.Context, in *PasskeyLoginFinishRequest, opts ...grpc.CallOption) (*PasskeyLoginFinishResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PasskeyLoginFinishResponse)
	err := c.cc.Invoke(ctx, AuthService_PasskeyLoginFinish_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*RefreshTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshTokenResponse)
	err := c.cc.Invoke(ctx, AuthService_RefreshToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogoutResponse)
	err := c.cc.Invoke(ctx, AuthService_Logout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
// All implementations must embed UnimplementedAuthServiceServer
// for forward compatibility.
type AuthServiceServer interface {
	SubmitEmail(context.Context, *SubmitEmailRequest) (*SubmitEmailResponse, error)
	VerifyEmailCode(context.Context, *VerifyEmailCodeRequest) (*VerifyEmailCodeResponse, error)
	PasskeyRegisterBegin(context.Context, *PasskeyRegisterBeginRequest) (*PasskeyRegisterBeginResponse, error)
	PasskeyRegisterFinish(context.Context, *PasskeyRegisterFinishRequest) (*PasskeyRegisterFinishResponse, error)
	PasskeyLoginBegin(context.Context, *PasskeyLoginBeginRequest) (*PasskeyLoginBeginResponse, error)
	PasskeyLoginFinish(context.Context, *PasskeyLoginFinishRequest) (*PasskeyLoginFinishResponse, error)
	RefreshToken(context.Context, *RefreshTokenRequest) (*RefreshTokenResponse, error)
	Logout(context.Context, *LogoutRequest) (*LogoutResponse, error)
	mustEmbedUnimplementedAuthServiceServer()
}

// UnimplementedAuthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthServiceServer struct{}

func (UnimplementedAuthServiceServer) SubmitEmail(context.Context, *SubmitEmailRequest) (*SubmitEmailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitEmail not implemented")
}
func (UnimplementedAuthServiceServer) VerifyEmailCode(context.Context, *VerifyEmailCodeRequest) (*VerifyEmailCodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyEmailCode not implemented")
}
func (UnimplementedAuthServiceServer) PasskeyRegisterBegin(context.Context, *PasskeyRegisterBeginRequest) (*PasskeyRegisterBeginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PasskeyRegisterBegin not implemented")
}
func (UnimplementedAuthServiceServer) PasskeyRegisterFinish(context.Context, *PasskeyRegisterFinishRequest) (*PasskeyRegisterFinishResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PasskeyRegisterFinish not implemented")
}
func (UnimplementedAuthServiceServer) PasskeyLoginBegin(context.Context, *PasskeyLoginBeginRequest) (*PasskeyLoginBeginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PasskeyLoginBegin not implemented")
}
func (UnimplementedAuthServiceServer) PasskeyLoginFinish(context.Context, *PasskeyLoginFinishRequest) (*PasskeyLoginFinishResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PasskeyLoginFinish not implemented")
}
func (UnimplementedAuthServiceServer) RefreshToken(context.Context, *RefreshTokenRequest) (*RefreshTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefreshToken not implemented")
}
func (UnimplementedAuthServiceServer) Logout(context.Context, *LogoutRequest) (*LogoutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Logout not implemented")
}
func (UnimplementedAuthServiceServer) mustEmbedUnimplementedAuthServiceServer() {}
func (UnimplementedAuthServiceServer) testEmbeddedByValue()                     {}

// UnsafeAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServiceServer will
// result in compilation errors.
type UnsafeAuthServiceServer interface {
	mustEmbedUnimplementedAuthServiceServer()
}

func RegisterAuthServiceServer(s grpc.ServiceRegistrar, srv AuthServiceServer) {
	// If the following call pancis, it indicates UnimplementedAuthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthService_ServiceDesc, srv)
}

func _AuthService_SubmitEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).SubmitEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_SubmitEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).SubmitEmail(ctx, req.(*SubmitEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_VerifyEmailCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyEmailCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).VerifyEmailCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_VerifyEmailCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).VerifyEmailCode(ctx, req.(*VerifyEmailCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_PasskeyRegisterBegin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PasskeyRegisterBeginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).PasskeyRegisterBegin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_PasskeyRegisterBegin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).PasskeyRegisterBegin(ctx, req.(*PasskeyRegisterBeginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_PasskeyRegisterFinish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PasskeyRegisterFinishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).PasskeyRegisterFinish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_PasskeyRegisterFinish_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).PasskeyRegisterFinish(ctx, req.(*PasskeyRegisterFinishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_PasskeyLoginBegin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PasskeyLoginBeginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).PasskeyLoginBegin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_PasskeyLoginBegin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).PasskeyLoginBegin(ctx, req.(*PasskeyLoginBeginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_PasskeyLoginFinish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PasskeyLoginFinishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).PasskeyLoginFinish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_PasskeyLoginFinish_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).PasskeyLoginFinish(ctx, req.(*PasskeyLoginFinishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_RefreshToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).RefreshToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_RefreshToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).RefreshToken(ctx, req.(*RefreshTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_Logout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Logout(ctx, req.(*LogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthService_ServiceDesc is the grpc.ServiceDesc for AuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitEmail",
			Handler:    _AuthService_SubmitEmail_Handler,
		},
		{
			MethodName: "VerifyEmailCode",
			Handler:    _AuthService_VerifyEmailCode_Handler,
		},
		{
			MethodName: "PasskeyRegisterBegin",
			Handler:    _AuthService_PasskeyRegisterBegin_Handler,
		},
		{
			MethodName: "PasskeyRegisterFinish",
			Handler:    _AuthService_PasskeyRegisterFinish_Handler,
		},
		{
			MethodName: "PasskeyLoginBegin",
			Handler:    _AuthService_PasskeyLoginBegin_Handler,
		},
		{
			MethodName: "PasskeyLoginFinish",
			Handler:    _AuthService_PasskeyLoginFinish_Handler,
		},
		{
			MethodName: "RefreshToken",
			Handler:    _AuthService_RefreshToken_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _AuthService_Logout_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.proto",
}
