apiVersion: v1
kind: Service
metadata:
  name: statistics-service
  labels:
    app: statistics-service
spec:
  selector:
    app: statistics-service
  ports:
    - name: grpc
      port: {{ .Values.service.port }}
      targetPort: grpc
  type: ClusterIP
