apiVersion: v1
kind: ServiceAccount
metadata:
  name: statistics-service-sa
  labels:
    app: statistics-service
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
