// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: user_stats.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
)

const getUserStats = `-- name: GetUserStats :one
SELECT user_id, total_likes, total_dislikes, battles_finished, updated_at
FROM user_stats
WHERE user_id = $1
`

func (q *Queries) GetUserStats(ctx context.Context, userID uuid.UUID) (UserStat, error) {
	row := q.db.QueryRowContext(ctx, getUserStats, userID)
	var i UserStat
	err := row.Scan(
		&i.UserID,
		&i.TotalLikes,
		&i.TotalDislikes,
		&i.BattlesFinished,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementBattlesFinished = `-- name: IncrementBattlesFinished :exec
INSERT INTO user_stats (user_id, battles_finished)
VALUES ($1, GREATEST($2, 0))
ON CONFLICT (user_id) DO UPDATE SET
 battles_finished = GREATEST(user_stats.battles_finished + $2, 0),
 updated_at = NOW()
`

type IncrementBattlesFinishedParams struct {
	UserID  uuid.UUID
	Column2 interface{}
}

func (q *Queries) IncrementBattlesFinished(ctx context.Context, arg IncrementBattlesFinishedParams) error {
	_, err := q.db.ExecContext(ctx, incrementBattlesFinished, arg.UserID, arg.Column2)
	return err
}

const incrementTotalDislikes = `-- name: IncrementTotalDislikes :exec
INSERT INTO user_stats (user_id, total_dislikes)
VALUES ($1, GREATEST($2, 0))
ON CONFLICT (user_id) DO UPDATE SET
 total_dislikes = GREATEST(user_stats.total_dislikes + $2, 0),
 updated_at = NOW()
`

type IncrementTotalDislikesParams struct {
	UserID  uuid.UUID
	Column2 interface{}
}

func (q *Queries) IncrementTotalDislikes(ctx context.Context, arg IncrementTotalDislikesParams) error {
	_, err := q.db.ExecContext(ctx, incrementTotalDislikes, arg.UserID, arg.Column2)
	return err
}

const incrementTotalLikes = `-- name: IncrementTotalLikes :exec
INSERT INTO user_stats (user_id, total_likes)
VALUES ($1, GREATEST($2, 0))
ON CONFLICT (user_id) DO UPDATE SET
 total_likes = GREATEST(user_stats.total_likes + $2, 0),
 updated_at = NOW()
`

type IncrementTotalLikesParams struct {
	UserID  uuid.UUID
	Column2 interface{}
}

func (q *Queries) IncrementTotalLikes(ctx context.Context, arg IncrementTotalLikesParams) error {
	_, err := q.db.ExecContext(ctx, incrementTotalLikes, arg.UserID, arg.Column2)
	return err
}
