apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-gateway-sa
  labels:
    app: api-gateway
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
