// Code generated by MockGen. DO NOT EDIT.
// Source: pinz/backend/api-gateway-service/internal/services (interfaces: AuthServiceInterface)
//
// Generated by this command:
//
//	mockgen -destination=auth_service_interface_mock.go -package=mocks pinz/backend/api-gateway-service/internal/services AuthServiceInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	proto "pinz/backend/api-gateway-service/pkg/proto"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAuthServiceInterface is a mock of AuthServiceInterface interface.
type MockAuthServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAuthServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockAuthServiceInterfaceMockRecorder is the mock recorder for MockAuthServiceInterface.
type MockAuthServiceInterfaceMockRecorder struct {
	mock *MockAuthServiceInterface
}

// NewMockAuthServiceInterface creates a new mock instance.
func NewMockAuthServiceInterface(ctrl *gomock.Controller) *MockAuthServiceInterface {
	mock := &MockAuthServiceInterface{ctrl: ctrl}
	mock.recorder = &MockAuthServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthServiceInterface) EXPECT() *MockAuthServiceInterfaceMockRecorder {
	return m.recorder
}

// DevLogin mocks base method.
func (m *MockAuthServiceInterface) DevLogin(ctx context.Context, email string) (*proto.DevLoginResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DevLogin", ctx, email)
	ret0, _ := ret[0].(*proto.DevLoginResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DevLogin indicates an expected call of DevLogin.
func (mr *MockAuthServiceInterfaceMockRecorder) DevLogin(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DevLogin", reflect.TypeOf((*MockAuthServiceInterface)(nil).DevLogin), ctx, email)
}

// Logout mocks base method.
func (m *MockAuthServiceInterface) Logout(ctx context.Context, refreshToken string) (*proto.LogoutResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout", ctx, refreshToken)
	ret0, _ := ret[0].(*proto.LogoutResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Logout indicates an expected call of Logout.
func (mr *MockAuthServiceInterfaceMockRecorder) Logout(ctx, refreshToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockAuthServiceInterface)(nil).Logout), ctx, refreshToken)
}

// PasskeyLoginBegin mocks base method.
func (m *MockAuthServiceInterface) PasskeyLoginBegin(ctx context.Context, email string) (*proto.PasskeyLoginBeginResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PasskeyLoginBegin", ctx, email)
	ret0, _ := ret[0].(*proto.PasskeyLoginBeginResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PasskeyLoginBegin indicates an expected call of PasskeyLoginBegin.
func (mr *MockAuthServiceInterfaceMockRecorder) PasskeyLoginBegin(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PasskeyLoginBegin", reflect.TypeOf((*MockAuthServiceInterface)(nil).PasskeyLoginBegin), ctx, email)
}

// PasskeyLoginFinish mocks base method.
func (m *MockAuthServiceInterface) PasskeyLoginFinish(ctx context.Context, email string, credentialJSON []byte) (*proto.PasskeyLoginFinishResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PasskeyLoginFinish", ctx, email, credentialJSON)
	ret0, _ := ret[0].(*proto.PasskeyLoginFinishResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PasskeyLoginFinish indicates an expected call of PasskeyLoginFinish.
func (mr *MockAuthServiceInterfaceMockRecorder) PasskeyLoginFinish(ctx, email, credentialJSON any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PasskeyLoginFinish", reflect.TypeOf((*MockAuthServiceInterface)(nil).PasskeyLoginFinish), ctx, email, credentialJSON)
}

// PasskeyRegisterBegin mocks base method.
func (m *MockAuthServiceInterface) PasskeyRegisterBegin(ctx context.Context, registrationID, username string) (*proto.PasskeyRegisterBeginResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PasskeyRegisterBegin", ctx, registrationID, username)
	ret0, _ := ret[0].(*proto.PasskeyRegisterBeginResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PasskeyRegisterBegin indicates an expected call of PasskeyRegisterBegin.
func (mr *MockAuthServiceInterfaceMockRecorder) PasskeyRegisterBegin(ctx, registrationID, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PasskeyRegisterBegin", reflect.TypeOf((*MockAuthServiceInterface)(nil).PasskeyRegisterBegin), ctx, registrationID, username)
}

// PasskeyRegisterFinish mocks base method.
func (m *MockAuthServiceInterface) PasskeyRegisterFinish(ctx context.Context, registrationID string, credentialJSON []byte) (*proto.PasskeyRegisterFinishResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PasskeyRegisterFinish", ctx, registrationID, credentialJSON)
	ret0, _ := ret[0].(*proto.PasskeyRegisterFinishResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PasskeyRegisterFinish indicates an expected call of PasskeyRegisterFinish.
func (mr *MockAuthServiceInterfaceMockRecorder) PasskeyRegisterFinish(ctx, registrationID, credentialJSON any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PasskeyRegisterFinish", reflect.TypeOf((*MockAuthServiceInterface)(nil).PasskeyRegisterFinish), ctx, registrationID, credentialJSON)
}

// RefreshToken mocks base method.
func (m *MockAuthServiceInterface) RefreshToken(ctx context.Context, refreshToken string) (*proto.RefreshTokenResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshToken", ctx, refreshToken)
	ret0, _ := ret[0].(*proto.RefreshTokenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefreshToken indicates an expected call of RefreshToken.
func (mr *MockAuthServiceInterfaceMockRecorder) RefreshToken(ctx, refreshToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshToken", reflect.TypeOf((*MockAuthServiceInterface)(nil).RefreshToken), ctx, refreshToken)
}

// SubmitEmail mocks base method.
func (m *MockAuthServiceInterface) SubmitEmail(ctx context.Context, email string) (*proto.SubmitEmailResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitEmail", ctx, email)
	ret0, _ := ret[0].(*proto.SubmitEmailResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubmitEmail indicates an expected call of SubmitEmail.
func (mr *MockAuthServiceInterfaceMockRecorder) SubmitEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitEmail", reflect.TypeOf((*MockAuthServiceInterface)(nil).SubmitEmail), ctx, email)
}

// VerifyEmailCode mocks base method.
func (m *MockAuthServiceInterface) VerifyEmailCode(ctx context.Context, registrationID, verificationCode string) (*proto.VerifyEmailCodeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyEmailCode", ctx, registrationID, verificationCode)
	ret0, _ := ret[0].(*proto.VerifyEmailCodeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyEmailCode indicates an expected call of VerifyEmailCode.
func (mr *MockAuthServiceInterfaceMockRecorder) VerifyEmailCode(ctx, registrationID, verificationCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyEmailCode", reflect.TypeOf((*MockAuthServiceInterface)(nil).VerifyEmailCode), ctx, registrationID, verificationCode)
}
