// Code generated by MockGen. DO NOT EDIT.
// Source: pinz/backend/api-gateway-service/internal/services (interfaces: AuthClient)
//
// Generated by this command:
//
//	mockgen -destination=auth_client_mock.go -package=mocks pinz/backend/api-gateway-service/internal/services AuthClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	proto "pinz/backend/api-gateway-service/pkg/proto"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAuthClient is a mock of AuthClient interface.
type MockAuthClient struct {
	ctrl     *gomock.Controller
	recorder *MockAuthClientMockRecorder
	isgomock struct{}
}

// MockAuthClientMockRecorder is the mock recorder for MockAuthClient.
type MockAuthClientMockRecorder struct {
	mock *MockAuthClient
}

// NewMockAuthClient creates a new mock instance.
func NewMockAuthClient(ctrl *gomock.Controller) *MockAuthClient {
	mock := &MockAuthClient{ctrl: ctrl}
	mock.recorder = &MockAuthClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthClient) EXPECT() *MockAuthClientMockRecorder {
	return m.recorder
}

// ChangeEmail mocks base method.
func (m *MockAuthClient) ChangeEmail(ctx context.Context, req *proto.ChangeEmailRequest) (*proto.ChangeEmailResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeEmail", ctx, req)
	ret0, _ := ret[0].(*proto.ChangeEmailResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChangeEmail indicates an expected call of ChangeEmail.
func (mr *MockAuthClientMockRecorder) ChangeEmail(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeEmail", reflect.TypeOf((*MockAuthClient)(nil).ChangeEmail), ctx, req)
}

// ConfirmAvatarUpload mocks base method.
func (m *MockAuthClient) ConfirmAvatarUpload(ctx context.Context, req *proto.ConfirmAvatarUploadRequest) (*proto.ConfirmAvatarUploadResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfirmAvatarUpload", ctx, req)
	ret0, _ := ret[0].(*proto.ConfirmAvatarUploadResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConfirmAvatarUpload indicates an expected call of ConfirmAvatarUpload.
func (mr *MockAuthClientMockRecorder) ConfirmAvatarUpload(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmAvatarUpload", reflect.TypeOf((*MockAuthClient)(nil).ConfirmAvatarUpload), ctx, req)
}

// ConfirmEmailChange mocks base method.
func (m *MockAuthClient) ConfirmEmailChange(ctx context.Context, req *proto.ConfirmEmailChangeRequest) (*proto.ConfirmEmailChangeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfirmEmailChange", ctx, req)
	ret0, _ := ret[0].(*proto.ConfirmEmailChangeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConfirmEmailChange indicates an expected call of ConfirmEmailChange.
func (mr *MockAuthClientMockRecorder) ConfirmEmailChange(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmEmailChange", reflect.TypeOf((*MockAuthClient)(nil).ConfirmEmailChange), ctx, req)
}

// CreateDesiredPlace mocks base method.
func (m *MockAuthClient) CreateDesiredPlace(ctx context.Context, req *proto.CreateDesiredPlaceRequest) (*proto.CreateDesiredPlaceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDesiredPlace", ctx, req)
	ret0, _ := ret[0].(*proto.CreateDesiredPlaceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDesiredPlace indicates an expected call of CreateDesiredPlace.
func (mr *MockAuthClientMockRecorder) CreateDesiredPlace(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDesiredPlace", reflect.TypeOf((*MockAuthClient)(nil).CreateDesiredPlace), ctx, req)
}

// DeleteAccount mocks base method.
func (m *MockAuthClient) DeleteAccount(ctx context.Context, req *proto.DeleteAccountRequest) (*proto.DeleteAccountResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAccount", ctx, req)
	ret0, _ := ret[0].(*proto.DeleteAccountResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteAccount indicates an expected call of DeleteAccount.
func (mr *MockAuthClientMockRecorder) DeleteAccount(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAccount", reflect.TypeOf((*MockAuthClient)(nil).DeleteAccount), ctx, req)
}

// DeleteAvatar mocks base method.
func (m *MockAuthClient) DeleteAvatar(ctx context.Context, req *proto.DeleteAvatarRequest) (*proto.DeleteAvatarResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAvatar", ctx, req)
	ret0, _ := ret[0].(*proto.DeleteAvatarResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteAvatar indicates an expected call of DeleteAvatar.
func (mr *MockAuthClientMockRecorder) DeleteAvatar(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAvatar", reflect.TypeOf((*MockAuthClient)(nil).DeleteAvatar), ctx, req)
}

// DeleteDesiredPlace mocks base method.
func (m *MockAuthClient) DeleteDesiredPlace(ctx context.Context, req *proto.DeleteDesiredPlaceRequest) (*proto.DeleteDesiredPlaceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDesiredPlace", ctx, req)
	ret0, _ := ret[0].(*proto.DeleteDesiredPlaceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteDesiredPlace indicates an expected call of DeleteDesiredPlace.
func (mr *MockAuthClientMockRecorder) DeleteDesiredPlace(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDesiredPlace", reflect.TypeOf((*MockAuthClient)(nil).DeleteDesiredPlace), ctx, req)
}

// DeleteDesiredPlaceImage mocks base method.
func (m *MockAuthClient) DeleteDesiredPlaceImage(ctx context.Context, req *proto.DeleteDesiredPlaceImageRequest) (*proto.DeleteDesiredPlaceImageResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDesiredPlaceImage", ctx, req)
	ret0, _ := ret[0].(*proto.DeleteDesiredPlaceImageResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteDesiredPlaceImage indicates an expected call of DeleteDesiredPlaceImage.
func (mr *MockAuthClientMockRecorder) DeleteDesiredPlaceImage(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDesiredPlaceImage", reflect.TypeOf((*MockAuthClient)(nil).DeleteDesiredPlaceImage), ctx, req)
}

// DevLogin mocks base method.
func (m *MockAuthClient) DevLogin(ctx context.Context, req *proto.DevLoginRequest) (*proto.DevLoginResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DevLogin", ctx, req)
	ret0, _ := ret[0].(*proto.DevLoginResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DevLogin indicates an expected call of DevLogin.
func (mr *MockAuthClientMockRecorder) DevLogin(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DevLogin", reflect.TypeOf((*MockAuthClient)(nil).DevLogin), ctx, req)
}

// GetProfile mocks base method.
func (m *MockAuthClient) GetProfile(ctx context.Context, req *proto.GetProfileRequest) (*proto.GetProfileResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProfile", ctx, req)
	ret0, _ := ret[0].(*proto.GetProfileResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProfile indicates an expected call of GetProfile.
func (mr *MockAuthClientMockRecorder) GetProfile(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfile", reflect.TypeOf((*MockAuthClient)(nil).GetProfile), ctx, req)
}

// GetPublicUserProfile mocks base method.
func (m *MockAuthClient) GetPublicUserProfile(ctx context.Context, req *proto.GetPublicUserProfileRequest) (*proto.GetPublicUserProfileResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPublicUserProfile", ctx, req)
	ret0, _ := ret[0].(*proto.GetPublicUserProfileResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPublicUserProfile indicates an expected call of GetPublicUserProfile.
func (mr *MockAuthClientMockRecorder) GetPublicUserProfile(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublicUserProfile", reflect.TypeOf((*MockAuthClient)(nil).GetPublicUserProfile), ctx, req)
}

// GetUsersProfiles mocks base method.
func (m *MockAuthClient) GetUsersProfiles(ctx context.Context, req *proto.GetUsersProfilesRequest) (*proto.GetUsersProfilesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersProfiles", ctx, req)
	ret0, _ := ret[0].(*proto.GetUsersProfilesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsersProfiles indicates an expected call of GetUsersProfiles.
func (mr *MockAuthClientMockRecorder) GetUsersProfiles(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersProfiles", reflect.TypeOf((*MockAuthClient)(nil).GetUsersProfiles), ctx, req)
}

// ListDesiredPlaces mocks base method.
func (m *MockAuthClient) ListDesiredPlaces(ctx context.Context, req *proto.ListDesiredPlacesRequest) (*proto.ListDesiredPlacesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDesiredPlaces", ctx, req)
	ret0, _ := ret[0].(*proto.ListDesiredPlacesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDesiredPlaces indicates an expected call of ListDesiredPlaces.
func (mr *MockAuthClientMockRecorder) ListDesiredPlaces(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDesiredPlaces", reflect.TypeOf((*MockAuthClient)(nil).ListDesiredPlaces), ctx, req)
}

// Logout mocks base method.
func (m *MockAuthClient) Logout(ctx context.Context, req *proto.LogoutRequest) (*proto.LogoutResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout", ctx, req)
	ret0, _ := ret[0].(*proto.LogoutResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Logout indicates an expected call of Logout.
func (mr *MockAuthClientMockRecorder) Logout(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockAuthClient)(nil).Logout), ctx, req)
}

// PasskeyLoginBegin mocks base method.
func (m *MockAuthClient) PasskeyLoginBegin(ctx context.Context, req *proto.PasskeyLoginBeginRequest) (*proto.PasskeyLoginBeginResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PasskeyLoginBegin", ctx, req)
	ret0, _ := ret[0].(*proto.PasskeyLoginBeginResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PasskeyLoginBegin indicates an expected call of PasskeyLoginBegin.
func (mr *MockAuthClientMockRecorder) PasskeyLoginBegin(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PasskeyLoginBegin", reflect.TypeOf((*MockAuthClient)(nil).PasskeyLoginBegin), ctx, req)
}

// PasskeyLoginFinish mocks base method.
func (m *MockAuthClient) PasskeyLoginFinish(ctx context.Context, req *proto.PasskeyLoginFinishRequest) (*proto.PasskeyLoginFinishResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PasskeyLoginFinish", ctx, req)
	ret0, _ := ret[0].(*proto.PasskeyLoginFinishResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PasskeyLoginFinish indicates an expected call of PasskeyLoginFinish.
func (mr *MockAuthClientMockRecorder) PasskeyLoginFinish(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PasskeyLoginFinish", reflect.TypeOf((*MockAuthClient)(nil).PasskeyLoginFinish), ctx, req)
}

// PasskeyRegisterBegin mocks base method.
func (m *MockAuthClient) PasskeyRegisterBegin(ctx context.Context, req *proto.PasskeyRegisterBeginRequest) (*proto.PasskeyRegisterBeginResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PasskeyRegisterBegin", ctx, req)
	ret0, _ := ret[0].(*proto.PasskeyRegisterBeginResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PasskeyRegisterBegin indicates an expected call of PasskeyRegisterBegin.
func (mr *MockAuthClientMockRecorder) PasskeyRegisterBegin(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PasskeyRegisterBegin", reflect.TypeOf((*MockAuthClient)(nil).PasskeyRegisterBegin), ctx, req)
}

// PasskeyRegisterFinish mocks base method.
func (m *MockAuthClient) PasskeyRegisterFinish(ctx context.Context, req *proto.PasskeyRegisterFinishRequest) (*proto.PasskeyRegisterFinishResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PasskeyRegisterFinish", ctx, req)
	ret0, _ := ret[0].(*proto.PasskeyRegisterFinishResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PasskeyRegisterFinish indicates an expected call of PasskeyRegisterFinish.
func (mr *MockAuthClientMockRecorder) PasskeyRegisterFinish(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PasskeyRegisterFinish", reflect.TypeOf((*MockAuthClient)(nil).PasskeyRegisterFinish), ctx, req)
}

// RefreshToken mocks base method.
func (m *MockAuthClient) RefreshToken(ctx context.Context, req *proto.RefreshTokenRequest) (*proto.RefreshTokenResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshToken", ctx, req)
	ret0, _ := ret[0].(*proto.RefreshTokenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefreshToken indicates an expected call of RefreshToken.
func (mr *MockAuthClientMockRecorder) RefreshToken(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshToken", reflect.TypeOf((*MockAuthClient)(nil).RefreshToken), ctx, req)
}

// RequestAvatarUpload mocks base method.
func (m *MockAuthClient) RequestAvatarUpload(ctx context.Context, req *proto.RequestAvatarUploadRequest) (*proto.RequestAvatarUploadResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestAvatarUpload", ctx, req)
	ret0, _ := ret[0].(*proto.RequestAvatarUploadResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RequestAvatarUpload indicates an expected call of RequestAvatarUpload.
func (mr *MockAuthClientMockRecorder) RequestAvatarUpload(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestAvatarUpload", reflect.TypeOf((*MockAuthClient)(nil).RequestAvatarUpload), ctx, req)
}

// RequestDesiredPlaceImageUpload mocks base method.
func (m *MockAuthClient) RequestDesiredPlaceImageUpload(ctx context.Context, req *proto.RequestDesiredPlaceImageUploadRequest) (*proto.RequestDesiredPlaceImageUploadResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestDesiredPlaceImageUpload", ctx, req)
	ret0, _ := ret[0].(*proto.RequestDesiredPlaceImageUploadResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RequestDesiredPlaceImageUpload indicates an expected call of RequestDesiredPlaceImageUpload.
func (mr *MockAuthClientMockRecorder) RequestDesiredPlaceImageUpload(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestDesiredPlaceImageUpload", reflect.TypeOf((*MockAuthClient)(nil).RequestDesiredPlaceImageUpload), ctx, req)
}

// SubmitEmail mocks base method.
func (m *MockAuthClient) SubmitEmail(ctx context.Context, req *proto.SubmitEmailRequest) (*proto.SubmitEmailResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitEmail", ctx, req)
	ret0, _ := ret[0].(*proto.SubmitEmailResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubmitEmail indicates an expected call of SubmitEmail.
func (mr *MockAuthClientMockRecorder) SubmitEmail(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitEmail", reflect.TypeOf((*MockAuthClient)(nil).SubmitEmail), ctx, req)
}

// UpdateDesiredPlace mocks base method.
func (m *MockAuthClient) UpdateDesiredPlace(ctx context.Context, req *proto.UpdateDesiredPlaceRequest) (*proto.UpdateDesiredPlaceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDesiredPlace", ctx, req)
	ret0, _ := ret[0].(*proto.UpdateDesiredPlaceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateDesiredPlace indicates an expected call of UpdateDesiredPlace.
func (mr *MockAuthClientMockRecorder) UpdateDesiredPlace(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDesiredPlace", reflect.TypeOf((*MockAuthClient)(nil).UpdateDesiredPlace), ctx, req)
}

// UpdateProfile mocks base method.
func (m *MockAuthClient) UpdateProfile(ctx context.Context, req *proto.UpdateProfileRequest) (*proto.UpdateProfileResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProfile", ctx, req)
	ret0, _ := ret[0].(*proto.UpdateProfileResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateProfile indicates an expected call of UpdateProfile.
func (mr *MockAuthClientMockRecorder) UpdateProfile(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProfile", reflect.TypeOf((*MockAuthClient)(nil).UpdateProfile), ctx, req)
}

// VerifyEmailCode mocks base method.
func (m *MockAuthClient) VerifyEmailCode(ctx context.Context, req *proto.VerifyEmailCodeRequest) (*proto.VerifyEmailCodeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyEmailCode", ctx, req)
	ret0, _ := ret[0].(*proto.VerifyEmailCodeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyEmailCode indicates an expected call of VerifyEmailCode.
func (mr *MockAuthClientMockRecorder) VerifyEmailCode(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyEmailCode", reflect.TypeOf((*MockAuthClient)(nil).VerifyEmailCode), ctx, req)
}
