// Code generated by MockGen. DO NOT EDIT.
// Source: pinz/backend/api-gateway-service/internal/handlers (interfaces: TripClient)
//
// Generated by this command:
//
//	mockgen -destination=trip_client_mock.go -package=mocks pinz/backend/api-gateway-service/internal/handlers TripClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	proto "pinz/backend/api-gateway-service/pkg/proto"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTripClient is a mock of TripClient interface.
type MockTripClient struct {
	ctrl     *gomock.Controller
	recorder *MockTripClientMockRecorder
	isgomock struct{}
}

// MockTripClientMockRecorder is the mock recorder for MockTripClient.
type MockTripClientMockRecorder struct {
	mock *MockTripClient
}

// NewMockTripClient creates a new mock instance.
func NewMockTripClient(ctrl *gomock.Controller) *MockTripClient {
	mock := &MockTripClient{ctrl: ctrl}
	mock.recorder = &MockTripClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTripClient) EXPECT() *MockTripClientMockRecorder {
	return m.recorder
}

// AddToFavourites mocks base method.
func (m *MockTripClient) AddToFavourites(ctx context.Context, req *proto.AddToFavouritesRequest) (*proto.AddToFavouritesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddToFavourites", ctx, req)
	ret0, _ := ret[0].(*proto.AddToFavouritesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddToFavourites indicates an expected call of AddToFavourites.
func (mr *MockTripClientMockRecorder) AddToFavourites(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddToFavourites", reflect.TypeOf((*MockTripClient)(nil).AddToFavourites), ctx, req)
}

// ApplyGroupsAndProcess mocks base method.
func (m *MockTripClient) ApplyGroupsAndProcess(ctx context.Context, req *proto.ApplyGroupsAndProcessRequest) (*proto.ApplyGroupsAndProcessResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyGroupsAndProcess", ctx, req)
	ret0, _ := ret[0].(*proto.ApplyGroupsAndProcessResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ApplyGroupsAndProcess indicates an expected call of ApplyGroupsAndProcess.
func (mr *MockTripClientMockRecorder) ApplyGroupsAndProcess(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyGroupsAndProcess", reflect.TypeOf((*MockTripClient)(nil).ApplyGroupsAndProcess), ctx, req)
}

// ConfirmTripCoverUpload mocks base method.
func (m *MockTripClient) ConfirmTripCoverUpload(ctx context.Context, req *proto.ConfirmTripCoverUploadRequest) (*proto.ConfirmTripCoverUploadResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfirmTripCoverUpload", ctx, req)
	ret0, _ := ret[0].(*proto.ConfirmTripCoverUploadResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConfirmTripCoverUpload indicates an expected call of ConfirmTripCoverUpload.
func (mr *MockTripClientMockRecorder) ConfirmTripCoverUpload(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmTripCoverUpload", reflect.TypeOf((*MockTripClient)(nil).ConfirmTripCoverUpload), ctx, req)
}

// CreateTrip mocks base method.
func (m *MockTripClient) CreateTrip(ctx context.Context, req *proto.CreateTripRequest) (*proto.CreateTripResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTrip", ctx, req)
	ret0, _ := ret[0].(*proto.CreateTripResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTrip indicates an expected call of CreateTrip.
func (mr *MockTripClientMockRecorder) CreateTrip(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTrip", reflect.TypeOf((*MockTripClient)(nil).CreateTrip), ctx, req)
}

// DeleteTrip mocks base method.
func (m *MockTripClient) DeleteTrip(ctx context.Context, req *proto.DeleteTripRequest) (*proto.DeleteTripResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTrip", ctx, req)
	ret0, _ := ret[0].(*proto.DeleteTripResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteTrip indicates an expected call of DeleteTrip.
func (mr *MockTripClientMockRecorder) DeleteTrip(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTrip", reflect.TypeOf((*MockTripClient)(nil).DeleteTrip), ctx, req)
}

// DeleteTripCover mocks base method.
func (m *MockTripClient) DeleteTripCover(ctx context.Context, req *proto.DeleteTripCoverRequest) (*proto.DeleteTripCoverResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTripCover", ctx, req)
	ret0, _ := ret[0].(*proto.DeleteTripCoverResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteTripCover indicates an expected call of DeleteTripCover.
func (mr *MockTripClientMockRecorder) DeleteTripCover(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTripCover", reflect.TypeOf((*MockTripClient)(nil).DeleteTripCover), ctx, req)
}

// DislikeTrip mocks base method.
func (m *MockTripClient) DislikeTrip(ctx context.Context, req *proto.DislikeTripRequest) (*proto.DislikeTripResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DislikeTrip", ctx, req)
	ret0, _ := ret[0].(*proto.DislikeTripResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DislikeTrip indicates an expected call of DislikeTrip.
func (mr *MockTripClientMockRecorder) DislikeTrip(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DislikeTrip", reflect.TypeOf((*MockTripClient)(nil).DislikeTrip), ctx, req)
}

// FinalizeTrip mocks base method.
func (m *MockTripClient) FinalizeTrip(ctx context.Context, req *proto.FinalizeTripRequest) (*proto.FinalizeTripResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FinalizeTrip", ctx, req)
	ret0, _ := ret[0].(*proto.FinalizeTripResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FinalizeTrip indicates an expected call of FinalizeTrip.
func (mr *MockTripClientMockRecorder) FinalizeTrip(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FinalizeTrip", reflect.TypeOf((*MockTripClient)(nil).FinalizeTrip), ctx, req)
}

// GenerateInviteLink mocks base method.
func (m *MockTripClient) GenerateInviteLink(ctx context.Context, req *proto.GenerateInviteLinkRequest) (*proto.GenerateInviteLinkResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateInviteLink", ctx, req)
	ret0, _ := ret[0].(*proto.GenerateInviteLinkResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateInviteLink indicates an expected call of GenerateInviteLink.
func (mr *MockTripClientMockRecorder) GenerateInviteLink(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateInviteLink", reflect.TypeOf((*MockTripClient)(nil).GenerateInviteLink), ctx, req)
}

// GetTrip mocks base method.
func (m *MockTripClient) GetTrip(ctx context.Context, req *proto.GetTripRequest) (*proto.GetTripResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTrip", ctx, req)
	ret0, _ := ret[0].(*proto.GetTripResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTrip indicates an expected call of GetTrip.
func (mr *MockTripClientMockRecorder) GetTrip(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTrip", reflect.TypeOf((*MockTripClient)(nil).GetTrip), ctx, req)
}

// GetTripReview mocks base method.
func (m *MockTripClient) GetTripReview(ctx context.Context, req *proto.GetTripReviewRequest) (*proto.GetTripReviewResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTripReview", ctx, req)
	ret0, _ := ret[0].(*proto.GetTripReviewResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTripReview indicates an expected call of GetTripReview.
func (mr *MockTripClientMockRecorder) GetTripReview(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTripReview", reflect.TypeOf((*MockTripClient)(nil).GetTripReview), ctx, req)
}

// JoinTripByToken mocks base method.
func (m *MockTripClient) JoinTripByToken(ctx context.Context, req *proto.JoinTripByTokenRequest) (*proto.JoinTripByTokenResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "JoinTripByToken", ctx, req)
	ret0, _ := ret[0].(*proto.JoinTripByTokenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// JoinTripByToken indicates an expected call of JoinTripByToken.
func (mr *MockTripClientMockRecorder) JoinTripByToken(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JoinTripByToken", reflect.TypeOf((*MockTripClient)(nil).JoinTripByToken), ctx, req)
}

// LeaveTrip mocks base method.
func (m *MockTripClient) LeaveTrip(ctx context.Context, req *proto.LeaveTripRequest) (*proto.LeaveTripResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LeaveTrip", ctx, req)
	ret0, _ := ret[0].(*proto.LeaveTripResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LeaveTrip indicates an expected call of LeaveTrip.
func (mr *MockTripClientMockRecorder) LeaveTrip(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LeaveTrip", reflect.TypeOf((*MockTripClient)(nil).LeaveTrip), ctx, req)
}

// LikeTrip mocks base method.
func (m *MockTripClient) LikeTrip(ctx context.Context, req *proto.LikeTripRequest) (*proto.LikeTripResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LikeTrip", ctx, req)
	ret0, _ := ret[0].(*proto.LikeTripResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LikeTrip indicates an expected call of LikeTrip.
func (mr *MockTripClientMockRecorder) LikeTrip(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LikeTrip", reflect.TypeOf((*MockTripClient)(nil).LikeTrip), ctx, req)
}

// ListFavourites mocks base method.
func (m *MockTripClient) ListFavourites(ctx context.Context, req *proto.ListFavouritesRequest) (*proto.ListFavouritesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFavourites", ctx, req)
	ret0, _ := ret[0].(*proto.ListFavouritesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFavourites indicates an expected call of ListFavourites.
func (mr *MockTripClientMockRecorder) ListFavourites(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFavourites", reflect.TypeOf((*MockTripClient)(nil).ListFavourites), ctx, req)
}

// ListFeed mocks base method.
func (m *MockTripClient) ListFeed(ctx context.Context, req *proto.ListFeedRequest) (*proto.ListFeedResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFeed", ctx, req)
	ret0, _ := ret[0].(*proto.ListFeedResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFeed indicates an expected call of ListFeed.
func (mr *MockTripClientMockRecorder) ListFeed(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFeed", reflect.TypeOf((*MockTripClient)(nil).ListFeed), ctx, req)
}

// ListUserTrips mocks base method.
func (m *MockTripClient) ListUserTrips(ctx context.Context, req *proto.ListUserTripsRequest) (*proto.ListUserTripsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUserTrips", ctx, req)
	ret0, _ := ret[0].(*proto.ListUserTripsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUserTrips indicates an expected call of ListUserTrips.
func (mr *MockTripClientMockRecorder) ListUserTrips(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUserTrips", reflect.TypeOf((*MockTripClient)(nil).ListUserTrips), ctx, req)
}

// ProcessMediaGrouping mocks base method.
func (m *MockTripClient) ProcessMediaGrouping(ctx context.Context, req *proto.ProcessMediaGroupingRequest) (*proto.ProcessMediaGroupingResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessMediaGrouping", ctx, req)
	ret0, _ := ret[0].(*proto.ProcessMediaGroupingResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProcessMediaGrouping indicates an expected call of ProcessMediaGrouping.
func (mr *MockTripClientMockRecorder) ProcessMediaGrouping(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessMediaGrouping", reflect.TypeOf((*MockTripClient)(nil).ProcessMediaGrouping), ctx, req)
}

// PublishTrip mocks base method.
func (m *MockTripClient) PublishTrip(ctx context.Context, req *proto.PublishTripRequest) (*proto.PublishTripResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishTrip", ctx, req)
	ret0, _ := ret[0].(*proto.PublishTripResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PublishTrip indicates an expected call of PublishTrip.
func (mr *MockTripClientMockRecorder) PublishTrip(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishTrip", reflect.TypeOf((*MockTripClient)(nil).PublishTrip), ctx, req)
}

// RemoveFromFavourites mocks base method.
func (m *MockTripClient) RemoveFromFavourites(ctx context.Context, req *proto.RemoveFromFavouritesRequest) (*proto.RemoveFromFavouritesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveFromFavourites", ctx, req)
	ret0, _ := ret[0].(*proto.RemoveFromFavouritesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveFromFavourites indicates an expected call of RemoveFromFavourites.
func (mr *MockTripClientMockRecorder) RemoveFromFavourites(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveFromFavourites", reflect.TypeOf((*MockTripClient)(nil).RemoveFromFavourites), ctx, req)
}

// RemoveParticipant mocks base method.
func (m *MockTripClient) RemoveParticipant(ctx context.Context, req *proto.RemoveParticipantRequest) (*proto.RemoveParticipantResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveParticipant", ctx, req)
	ret0, _ := ret[0].(*proto.RemoveParticipantResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveParticipant indicates an expected call of RemoveParticipant.
func (mr *MockTripClientMockRecorder) RemoveParticipant(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveParticipant", reflect.TypeOf((*MockTripClient)(nil).RemoveParticipant), ctx, req)
}

// RequestTripCoverUpload mocks base method.
func (m *MockTripClient) RequestTripCoverUpload(ctx context.Context, req *proto.RequestTripCoverUploadRequest) (*proto.RequestTripCoverUploadResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestTripCoverUpload", ctx, req)
	ret0, _ := ret[0].(*proto.RequestTripCoverUploadResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RequestTripCoverUpload indicates an expected call of RequestTripCoverUpload.
func (mr *MockTripClientMockRecorder) RequestTripCoverUpload(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestTripCoverUpload", reflect.TypeOf((*MockTripClient)(nil).RequestTripCoverUpload), ctx, req)
}

// UpdateTrip mocks base method.
func (m *MockTripClient) UpdateTrip(ctx context.Context, req *proto.UpdateTripRequest) (*proto.UpdateTripResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTrip", ctx, req)
	ret0, _ := ret[0].(*proto.UpdateTripResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTrip indicates an expected call of UpdateTrip.
func (mr *MockTripClientMockRecorder) UpdateTrip(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTrip", reflect.TypeOf((*MockTripClient)(nil).UpdateTrip), ctx, req)
}

// UpdateTripSettings mocks base method.
func (m *MockTripClient) UpdateTripSettings(ctx context.Context, req *proto.UpdateTripSettingsRequest) (*proto.UpdateTripSettingsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTripSettings", ctx, req)
	ret0, _ := ret[0].(*proto.UpdateTripSettingsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTripSettings indicates an expected call of UpdateTripSettings.
func (mr *MockTripClientMockRecorder) UpdateTripSettings(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTripSettings", reflect.TypeOf((*MockTripClient)(nil).UpdateTripSettings), ctx, req)
}
