// Code generated by MockGen. DO NOT EDIT.
// Source: pinz/backend/statistics-service/internal/repositories (interfaces: EventLogRepositoryInterface)
//
// Generated by this command:
//
//	mockgen -destination=event_log_repository_mock.go -package=mocks pinz/backend/statistics-service/internal/repositories EventLogRepositoryInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockEventLogRepositoryInterface is a mock of EventLogRepositoryInterface interface.
type MockEventLogRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockEventLogRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockEventLogRepositoryInterfaceMockRecorder is the mock recorder for MockEventLogRepositoryInterface.
type MockEventLogRepositoryInterfaceMockRecorder struct {
	mock *MockEventLogRepositoryInterface
}

// NewMockEventLogRepositoryInterface creates a new mock instance.
func NewMockEventLogRepositoryInterface(ctrl *gomock.Controller) *MockEventLogRepositoryInterface {
	mock := &MockEventLogRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockEventLogRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventLogRepositoryInterface) EXPECT() *MockEventLogRepositoryInterfaceMockRecorder {
	return m.recorder
}

// IsProcessed mocks base method.
func (m *MockEventLogRepositoryInterface) IsProcessed(ctx context.Context, eventID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsProcessed", ctx, eventID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsProcessed indicates an expected call of IsProcessed.
func (mr *MockEventLogRepositoryInterfaceMockRecorder) IsProcessed(ctx, eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsProcessed", reflect.TypeOf((*MockEventLogRepositoryInterface)(nil).IsProcessed), ctx, eventID)
}

// MarkProcessed mocks base method.
func (m *MockEventLogRepositoryInterface) MarkProcessed(ctx context.Context, eventID, eventType string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkProcessed", ctx, eventID, eventType)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkProcessed indicates an expected call of MarkProcessed.
func (mr *MockEventLogRepositoryInterfaceMockRecorder) MarkProcessed(ctx, eventID, eventType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkProcessed", reflect.TypeOf((*MockEventLogRepositoryInterface)(nil).MarkProcessed), ctx, eventID, eventType)
}
