// Code generated by MockGen. DO NOT EDIT.
// Source: pinz/backend/statistics-service/internal/repositories (interfaces: GeoRegistryRepositoryInterface)
//
// Generated by this command:
//
//	mockgen -destination=geo_registry_repository_mock.go -package=mocks pinz/backend/statistics-service/internal/repositories GeoRegistryRepositoryInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "pinz/backend/statistics-service/internal/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGeoRegistryRepositoryInterface is a mock of GeoRegistryRepositoryInterface interface.
type MockGeoRegistryRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockGeoRegistryRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockGeoRegistryRepositoryInterfaceMockRecorder is the mock recorder for MockGeoRegistryRepositoryInterface.
type MockGeoRegistryRepositoryInterfaceMockRecorder struct {
	mock *MockGeoRegistryRepositoryInterface
}

// NewMockGeoRegistryRepositoryInterface creates a new mock instance.
func NewMockGeoRegistryRepositoryInterface(ctrl *gomock.Controller) *MockGeoRegistryRepositoryInterface {
	mock := &MockGeoRegistryRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockGeoRegistryRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGeoRegistryRepositoryInterface) EXPECT() *MockGeoRegistryRepositoryInterfaceMockRecorder {
	return m.recorder
}

// EnsureByName mocks base method.
func (m *MockGeoRegistryRepositoryInterface) EnsureByName(ctx context.Context, countryName, cityName string) (*models.GeoLocation, *models.GeoLocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureByName", ctx, countryName, cityName)
	ret0, _ := ret[0].(*models.GeoLocation)
	ret1, _ := ret[1].(*models.GeoLocation)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// EnsureByName indicates an expected call of EnsureByName.
func (mr *MockGeoRegistryRepositoryInterfaceMockRecorder) EnsureByName(ctx, countryName, cityName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureByName", reflect.TypeOf((*MockGeoRegistryRepositoryInterface)(nil).EnsureByName), ctx, countryName, cityName)
}

// GetByID mocks base method.
func (m *MockGeoRegistryRepositoryInterface) GetByID(ctx context.Context, id int32) (*models.GeoLocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.GeoLocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockGeoRegistryRepositoryInterfaceMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockGeoRegistryRepositoryInterface)(nil).GetByID), ctx, id)
}

// Upsert mocks base method.
func (m *MockGeoRegistryRepositoryInterface) Upsert(ctx context.Context, loc *models.GeoLocation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, loc)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockGeoRegistryRepositoryInterfaceMockRecorder) Upsert(ctx, loc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockGeoRegistryRepositoryInterface)(nil).Upsert), ctx, loc)
}
