// Code generated by MockGen. DO NOT EDIT.
// Source: pinz/backend/statistics-service/internal/repositories (interfaces: TripLocationsRepositoryInterface)
//
// Generated by this command:
//
//	mockgen -destination=trip_locations_repository_mock.go -package=mocks pinz/backend/statistics-service/internal/repositories TripLocationsRepositoryInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "pinz/backend/statistics-service/internal/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTripLocationsRepositoryInterface is a mock of TripLocationsRepositoryInterface interface.
type MockTripLocationsRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockTripLocationsRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockTripLocationsRepositoryInterfaceMockRecorder is the mock recorder for MockTripLocationsRepositoryInterface.
type MockTripLocationsRepositoryInterfaceMockRecorder struct {
	mock *MockTripLocationsRepositoryInterface
}

// NewMockTripLocationsRepositoryInterface creates a new mock instance.
func NewMockTripLocationsRepositoryInterface(ctrl *gomock.Controller) *MockTripLocationsRepositoryInterface {
	mock := &MockTripLocationsRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockTripLocationsRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTripLocationsRepositoryInterface) EXPECT() *MockTripLocationsRepositoryInterfaceMockRecorder {
	return m.recorder
}

// AggregateVisitedByTripIDs mocks base method.
func (m *MockTripLocationsRepositoryInterface) AggregateVisitedByTripIDs(ctx context.Context, tripIDs []string, typeFilter string) ([]*models.VisitedLocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AggregateVisitedByTripIDs", ctx, tripIDs, typeFilter)
	ret0, _ := ret[0].([]*models.VisitedLocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AggregateVisitedByTripIDs indicates an expected call of AggregateVisitedByTripIDs.
func (mr *MockTripLocationsRepositoryInterfaceMockRecorder) AggregateVisitedByTripIDs(ctx, tripIDs, typeFilter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AggregateVisitedByTripIDs", reflect.TypeOf((*MockTripLocationsRepositoryInterface)(nil).AggregateVisitedByTripIDs), ctx, tripIDs, typeFilter)
}

// DeleteByTripID mocks base method.
func (m *MockTripLocationsRepositoryInterface) DeleteByTripID(ctx context.Context, tripID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByTripID", ctx, tripID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByTripID indicates an expected call of DeleteByTripID.
func (mr *MockTripLocationsRepositoryInterfaceMockRecorder) DeleteByTripID(ctx, tripID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByTripID", reflect.TypeOf((*MockTripLocationsRepositoryInterface)(nil).DeleteByTripID), ctx, tripID)
}

// Upsert mocks base method.
func (m *MockTripLocationsRepositoryInterface) Upsert(ctx context.Context, tripID string, locationID int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, tripID, locationID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockTripLocationsRepositoryInterfaceMockRecorder) Upsert(ctx, tripID, locationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockTripLocationsRepositoryInterface)(nil).Upsert), ctx, tripID, locationID)
}
