// Code generated by MockGen. DO NOT EDIT.
// Source: pinz/backend/statistics-service/internal/repositories (interfaces: UserStatsRepositoryInterface)
//
// Generated by this command:
//
//	mockgen -destination=user_stats_repository_mock.go -package=mocks pinz/backend/statistics-service/internal/repositories UserStatsRepositoryInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "pinz/backend/statistics-service/internal/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUserStatsRepositoryInterface is a mock of UserStatsRepositoryInterface interface.
type MockUserStatsRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUserStatsRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockUserStatsRepositoryInterfaceMockRecorder is the mock recorder for MockUserStatsRepositoryInterface.
type MockUserStatsRepositoryInterfaceMockRecorder struct {
	mock *MockUserStatsRepositoryInterface
}

// NewMockUserStatsRepositoryInterface creates a new mock instance.
func NewMockUserStatsRepositoryInterface(ctrl *gomock.Controller) *MockUserStatsRepositoryInterface {
	mock := &MockUserStatsRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockUserStatsRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserStatsRepositoryInterface) EXPECT() *MockUserStatsRepositoryInterfaceMockRecorder {
	return m.recorder
}

// GetByUserID mocks base method.
func (m *MockUserStatsRepositoryInterface) GetByUserID(ctx context.Context, userID string) (*models.UserStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", ctx, userID)
	ret0, _ := ret[0].(*models.UserStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockUserStatsRepositoryInterfaceMockRecorder) GetByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockUserStatsRepositoryInterface)(nil).GetByUserID), ctx, userID)
}

// IncrementBattles mocks base method.
func (m *MockUserStatsRepositoryInterface) IncrementBattles(ctx context.Context, userID string, delta int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementBattles", ctx, userID, delta)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementBattles indicates an expected call of IncrementBattles.
func (mr *MockUserStatsRepositoryInterfaceMockRecorder) IncrementBattles(ctx, userID, delta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementBattles", reflect.TypeOf((*MockUserStatsRepositoryInterface)(nil).IncrementBattles), ctx, userID, delta)
}

// IncrementDislikes mocks base method.
func (m *MockUserStatsRepositoryInterface) IncrementDislikes(ctx context.Context, userID string, delta int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementDislikes", ctx, userID, delta)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementDislikes indicates an expected call of IncrementDislikes.
func (mr *MockUserStatsRepositoryInterfaceMockRecorder) IncrementDislikes(ctx, userID, delta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementDislikes", reflect.TypeOf((*MockUserStatsRepositoryInterface)(nil).IncrementDislikes), ctx, userID, delta)
}

// IncrementLikes mocks base method.
func (m *MockUserStatsRepositoryInterface) IncrementLikes(ctx context.Context, userID string, delta int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementLikes", ctx, userID, delta)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementLikes indicates an expected call of IncrementLikes.
func (mr *MockUserStatsRepositoryInterfaceMockRecorder) IncrementLikes(ctx, userID, delta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementLikes", reflect.TypeOf((*MockUserStatsRepositoryInterface)(nil).IncrementLikes), ctx, userID, delta)
}
