apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      imagePullSecrets:
        - name: docker-registry-secret
      containers:
        - name: auth-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
              name: grpc
          env:
            - name: GRPC_PORT
              value: {{ .Values.env.grpcPort | quote }}
            - name: DB_HOST
              value: {{ .Values.env.dbHost | quote }}
            - name: DB_PORT
              value: {{ .Values.env.dbPort | quote }}
            - name: DB_USER
              value: {{ .Values.env.dbUser | quote }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-service-secret
                  key: db-password
            - name: DB_NAME
              value: {{ .Values.env.dbName | quote }}
            - name: REDIS_ADDR
              value: {{ .Values.env.redisAddr | quote }}
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: auth-service-secret
                  key: jwt-secret-key
