apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
type: Opaque
stringData:
  db-password: {{ .Values.secret.dbPassword | quote }}
  jwt-secret-key: {{ .Values.secret.jwtSecretKey | quote }}
  smtp-username: {{ .Values.secret.smtpUsername | quote }}
  smtp-password: {{ .Values.secret.smtpPassword | quote }}
  s3-access-key: {{ .Values.secret.s3AccessKey | quote }}
  s3-secret-key: {{ .Values.secret.s3SecretKey | quote }}