apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
type: Opaque
stringData:
  db-password: {{ .Values.secret.dbPassword | quote }}
  jwt-secret-key: {{ .Values.secret.jwtSecretKey | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-secret
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: {{ .Values.dockerConfig | toJson | quote }}
