basePath: /
definitions:
  pinz_backend_api-gateway-service_internal_requests.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  pinz_backend_api-gateway-service_internal_requests.LogoutRequest:
    properties:
      refresh_token:
        type: string
    type: object
  pinz_backend_api-gateway-service_internal_requests.RefreshTokenRequest:
    properties:
      refresh_token:
        type: string
    type: object
  pinz_backend_api-gateway-service_internal_requests.SetPasswordAndUsernameRequest:
    properties:
      password:
        type: string
      registration_id:
        type: string
      username:
        type: string
    type: object
  pinz_backend_api-gateway-service_internal_requests.SubmitEmailRequest:
    properties:
      email:
        example: user@example.com
        type: string
    type: object
  pinz_backend_api-gateway-service_internal_requests.VerifyEmailCodeRequest:
    properties:
      registration_id:
        type: string
      verification_code:
        type: string
    type: object
  pinz_backend_api-gateway-service_internal_responses.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  pinz_backend_api-gateway-service_internal_responses.LoginResponse:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
    type: object
  pinz_backend_api-gateway-service_internal_responses.LogoutResponse:
    properties:
      success:
        type: boolean
    type: object
  pinz_backend_api-gateway-service_internal_responses.RefreshTokenResponse:
    properties:
      access_token:
        type: string
    type: object
  pinz_backend_api-gateway-service_internal_responses.SetPasswordAndUsernameResponse:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
    type: object
  pinz_backend_api-gateway-service_internal_responses.SubmitEmailResponse:
    properties:
      is_registered:
        type: boolean
      registration_key:
        example: 550e8400-e29b-41d4-a716-446655440000
        type: string
    type: object
  pinz_backend_api-gateway-service_internal_responses.VerifyEmailCodeResponse:
    properties:
      success:
        type: boolean
    type: object
host: pinz.website
info:
  contact: {}
  description: API Gateway for Pinz mobile client
  title: Pinz API Gateway
  version: "1.0"
paths:
  /api/v1/auth/email:
    post:
      consumes:
      - application/json
      description: 'User sends email. Response indicates if user is registered (next
        step: password) or not (next step: code from email). registration_key is set
        only when is_registered is false.'
      parameters:
      - description: Email
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/pinz_backend_api-gateway-service_internal_requests.SubmitEmailRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pinz_backend_api-gateway-service_internal_responses.SubmitEmailResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/pinz_backend_api-gateway-service_internal_responses.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/pinz_backend_api-gateway-service_internal_responses.ErrorResponse'
      summary: Submit email (login or registration flow)
      tags:
      - auth
  /api/v1/auth/finish-register:
    post:
      consumes:
      - application/json
      parameters:
      - description: Registration ID, password, username
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/pinz_backend_api-gateway-service_internal_requests.SetPasswordAndUsernameRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pinz_backend_api-gateway-service_internal_responses.SetPasswordAndUsernameResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/pinz_backend_api-gateway-service_internal_responses.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/pinz_backend_api-gateway-service_internal_responses.ErrorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/pinz_backend_api-gateway-service_internal_responses.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/pinz_backend_api-gateway-service_internal_responses.ErrorResponse'
      summary: Set password and username (finish registration)
      tags:
      - auth
  /api/v1/auth/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: Email and password
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/pinz_backend_api-gateway-service_internal_requests.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pinz_backend_api-gateway-service_internal_responses.LoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/pinz_backend_api-gateway-service_internal_responses.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/pinz_backend_api-gateway-service_internal_responses.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/pinz_backend_api-gateway-service_internal_responses.ErrorResponse'
      summary: Login
      tags:
      - auth
  /api/v1/auth/logout:
    post:
      consumes:
      - application/json
      parameters:
      - description: Refresh token
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/pinz_backend_api-gateway-service_internal_requests.LogoutRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pinz_backend_api-gateway-service_internal_responses.LogoutResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/pinz_backend_api-gateway-service_internal_responses.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/pinz_backend_api-gateway-service_internal_responses.ErrorResponse'
      summary: Logout
      tags:
      - auth
  /api/v1/auth/refresh:
    post:
      consumes:
      - application/json
      parameters:
      - description: Refresh token
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/pinz_backend_api-gateway-service_internal_requests.RefreshTokenRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pinz_backend_api-gateway-service_internal_responses.RefreshTokenResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/pinz_backend_api-gateway-service_internal_responses.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/pinz_backend_api-gateway-service_internal_responses.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/pinz_backend_api-gateway-service_internal_responses.ErrorResponse'
      summary: Refresh access token
      tags:
      - auth
  /api/v1/auth/verify-email:
    post:
      consumes:
      - application/json
      parameters:
      - description: Registration ID and code
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/pinz_backend_api-gateway-service_internal_requests.VerifyEmailCodeRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pinz_backend_api-gateway-service_internal_responses.VerifyEmailCodeResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/pinz_backend_api-gateway-service_internal_responses.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/pinz_backend_api-gateway-service_internal_responses.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/pinz_backend_api-gateway-service_internal_responses.ErrorResponse'
      summary: Verify email code
      tags:
      - auth
swagger: "2.0"
