// Code generated by MockGen. DO NOT EDIT.
// Source: pinz/backend/auth-service/internal/services (interfaces: DesiredPlaceRepositoryInterface)
//
// Generated by this command:
//
//	mockgen -destination=desired_place_repository_mock.go -package=mocks pinz/backend/auth-service/internal/services DesiredPlaceRepositoryInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	models "pinz/backend/auth-service/internal/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDesiredPlaceRepositoryInterface is a mock of DesiredPlaceRepositoryInterface interface.
type MockDesiredPlaceRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockDesiredPlaceRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockDesiredPlaceRepositoryInterfaceMockRecorder is the mock recorder for MockDesiredPlaceRepositoryInterface.
type MockDesiredPlaceRepositoryInterfaceMockRecorder struct {
	mock *MockDesiredPlaceRepositoryInterface
}

// NewMockDesiredPlaceRepositoryInterface creates a new mock instance.
func NewMockDesiredPlaceRepositoryInterface(ctrl *gomock.Controller) *MockDesiredPlaceRepositoryInterface {
	mock := &MockDesiredPlaceRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockDesiredPlaceRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDesiredPlaceRepositoryInterface) EXPECT() *MockDesiredPlaceRepositoryInterfaceMockRecorder {
	return m.recorder
}

// ClearImage mocks base method.
func (m *MockDesiredPlaceRepositoryInterface) ClearImage(placeID string) (*models.DesiredPlace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearImage", placeID)
	ret0, _ := ret[0].(*models.DesiredPlace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClearImage indicates an expected call of ClearImage.
func (mr *MockDesiredPlaceRepositoryInterfaceMockRecorder) ClearImage(placeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearImage", reflect.TypeOf((*MockDesiredPlaceRepositoryInterface)(nil).ClearImage), placeID)
}

// Create mocks base method.
func (m *MockDesiredPlaceRepositoryInterface) Create(p *models.DesiredPlace) (*models.DesiredPlace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", p)
	ret0, _ := ret[0].(*models.DesiredPlace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockDesiredPlaceRepositoryInterfaceMockRecorder) Create(p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDesiredPlaceRepositoryInterface)(nil).Create), p)
}

// Delete mocks base method.
func (m *MockDesiredPlaceRepositoryInterface) Delete(placeID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", placeID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDesiredPlaceRepositoryInterfaceMockRecorder) Delete(placeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDesiredPlaceRepositoryInterface)(nil).Delete), placeID)
}

// GetByID mocks base method.
func (m *MockDesiredPlaceRepositoryInterface) GetByID(placeID string) (*models.DesiredPlace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", placeID)
	ret0, _ := ret[0].(*models.DesiredPlace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockDesiredPlaceRepositoryInterfaceMockRecorder) GetByID(placeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockDesiredPlaceRepositoryInterface)(nil).GetByID), placeID)
}

// ListByUserID mocks base method.
func (m *MockDesiredPlaceRepositoryInterface) ListByUserID(userID string) ([]*models.DesiredPlace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUserID", userID)
	ret0, _ := ret[0].([]*models.DesiredPlace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUserID indicates an expected call of ListByUserID.
func (mr *MockDesiredPlaceRepositoryInterfaceMockRecorder) ListByUserID(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUserID", reflect.TypeOf((*MockDesiredPlaceRepositoryInterface)(nil).ListByUserID), userID)
}

// Update mocks base method.
func (m *MockDesiredPlaceRepositoryInterface) Update(placeID, name, description, imageURL string) (*models.DesiredPlace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", placeID, name, description, imageURL)
	ret0, _ := ret[0].(*models.DesiredPlace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockDesiredPlaceRepositoryInterfaceMockRecorder) Update(placeID, name, description, imageURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDesiredPlaceRepositoryInterface)(nil).Update), placeID, name, description, imageURL)
}

// UpdateContent mocks base method.
func (m *MockDesiredPlaceRepositoryInterface) UpdateContent(placeID, name, description string) (*models.DesiredPlace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateContent", placeID, name, description)
	ret0, _ := ret[0].(*models.DesiredPlace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateContent indicates an expected call of UpdateContent.
func (mr *MockDesiredPlaceRepositoryInterfaceMockRecorder) UpdateContent(placeID, name, description any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateContent", reflect.TypeOf((*MockDesiredPlaceRepositoryInterface)(nil).UpdateContent), placeID, name, description)
}
