// Code generated by MockGen. DO NOT EDIT.
// Source: pinz/backend/auth-service/internal/services (interfaces: RedisRepositoryInterface)
//
// Generated by this command:
//
//	mockgen -destination=redis_repository_mock.go -package=mocks pinz/backend/auth-service/internal/services RedisRepositoryInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockRedisRepositoryInterface is a mock of RedisRepositoryInterface interface.
type MockRedisRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRedisRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockRedisRepositoryInterfaceMockRecorder is the mock recorder for MockRedisRepositoryInterface.
type MockRedisRepositoryInterfaceMockRecorder struct {
	mock *MockRedisRepositoryInterface
}

// NewMockRedisRepositoryInterface creates a new mock instance.
func NewMockRedisRepositoryInterface(ctrl *gomock.Controller) *MockRedisRepositoryInterface {
	mock := &MockRedisRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockRedisRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRedisRepositoryInterface) EXPECT() *MockRedisRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Del mocks base method.
func (m *MockRedisRepositoryInterface) Del(ctx context.Context, keys ...string) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range keys {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Del", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Del indicates an expected call of Del.
func (mr *MockRedisRepositoryInterfaceMockRecorder) Del(ctx any, keys ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, keys...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Del", reflect.TypeOf((*MockRedisRepositoryInterface)(nil).Del), varargs...)
}

// Expire mocks base method.
func (m *MockRedisRepositoryInterface) Expire(ctx context.Context, key string, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Expire", ctx, key, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// Expire indicates an expected call of Expire.
func (mr *MockRedisRepositoryInterfaceMockRecorder) Expire(ctx, key, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Expire", reflect.TypeOf((*MockRedisRepositoryInterface)(nil).Expire), ctx, key, ttl)
}

// Get mocks base method.
func (m *MockRedisRepositoryInterface) Get(ctx context.Context, key string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, key)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRedisRepositoryInterfaceMockRecorder) Get(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRedisRepositoryInterface)(nil).Get), ctx, key)
}

// HGetAll mocks base method.
func (m *MockRedisRepositoryInterface) HGetAll(ctx context.Context, key string) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HGetAll", ctx, key)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HGetAll indicates an expected call of HGetAll.
func (mr *MockRedisRepositoryInterfaceMockRecorder) HGetAll(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HGetAll", reflect.TypeOf((*MockRedisRepositoryInterface)(nil).HGetAll), ctx, key)
}

// HSet mocks base method.
func (m *MockRedisRepositoryInterface) HSet(ctx context.Context, key string, values ...any) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, key}
	for _, a := range values {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "HSet", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// HSet indicates an expected call of HSet.
func (mr *MockRedisRepositoryInterfaceMockRecorder) HSet(ctx, key any, values ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, key}, values...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HSet", reflect.TypeOf((*MockRedisRepositoryInterface)(nil).HSet), varargs...)
}

// SetEX mocks base method.
func (m *MockRedisRepositoryInterface) SetEX(ctx context.Context, key string, value any, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetEX", ctx, key, value, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetEX indicates an expected call of SetEX.
func (mr *MockRedisRepositoryInterfaceMockRecorder) SetEX(ctx, key, value, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetEX", reflect.TypeOf((*MockRedisRepositoryInterface)(nil).SetEX), ctx, key, value, ttl)
}
