// Code generated by MockGen. DO NOT EDIT.
// Source: pinz/backend/auth-service/internal/services (interfaces: S3Uploader)
//
// Generated by this command:
//
//	mockgen -destination=s3_uploader_mock.go -package=mocks pinz/backend/auth-service/internal/services S3Uploader
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockS3Uploader is a mock of S3Uploader interface.
type MockS3Uploader struct {
	ctrl     *gomock.Controller
	recorder *MockS3UploaderMockRecorder
	isgomock struct{}
}

// MockS3UploaderMockRecorder is the mock recorder for MockS3Uploader.
type MockS3UploaderMockRecorder struct {
	mock *MockS3Uploader
}

// NewMockS3Uploader creates a new mock instance.
func NewMockS3Uploader(ctrl *gomock.Controller) *MockS3Uploader {
	mock := &MockS3Uploader{ctrl: ctrl}
	mock.recorder = &MockS3UploaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockS3Uploader) EXPECT() *MockS3UploaderMockRecorder {
	return m.recorder
}

// DeleteObject mocks base method.
func (m *MockS3Uploader) DeleteObject(ctx context.Context, s3Key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteObject", ctx, s3Key)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteObject indicates an expected call of DeleteObject.
func (mr *MockS3UploaderMockRecorder) DeleteObject(ctx, s3Key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteObject", reflect.TypeOf((*MockS3Uploader)(nil).DeleteObject), ctx, s3Key)
}

// PresignedUploadURL mocks base method.
func (m *MockS3Uploader) PresignedUploadURL(ctx context.Context, s3Key, contentType string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PresignedUploadURL", ctx, s3Key, contentType)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PresignedUploadURL indicates an expected call of PresignedUploadURL.
func (mr *MockS3UploaderMockRecorder) PresignedUploadURL(ctx, s3Key, contentType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PresignedUploadURL", reflect.TypeOf((*MockS3Uploader)(nil).PresignedUploadURL), ctx, s3Key, contentType)
}

// ReadURL mocks base method.
func (m *MockS3Uploader) ReadURL(ctx context.Context, s3Key string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadURL", ctx, s3Key)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadURL indicates an expected call of ReadURL.
func (mr *MockS3UploaderMockRecorder) ReadURL(ctx, s3Key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadURL", reflect.TypeOf((*MockS3Uploader)(nil).ReadURL), ctx, s3Key)
}
