// Code generated by MockGen. DO NOT EDIT.
// Source: pinz/backend/trip-service/internal/services (interfaces: MediaURLResolver)
//
// Generated by this command:
//
//	mockgen -destination=media_url_resolver_mock.go -package=mocks pinz/backend/trip-service/internal/services MediaURLResolver
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockMediaURLResolver is a mock of MediaURLResolver interface.
type MockMediaURLResolver struct {
	ctrl     *gomock.Controller
	recorder *MockMediaURLResolverMockRecorder
	isgomock struct{}
}

// MockMediaURLResolverMockRecorder is the mock recorder for MockMediaURLResolver.
type MockMediaURLResolverMockRecorder struct {
	mock *MockMediaURLResolver
}

// NewMockMediaURLResolver creates a new mock instance.
func NewMockMediaURLResolver(ctrl *gomock.Controller) *MockMediaURLResolver {
	mock := &MockMediaURLResolver{ctrl: ctrl}
	mock.recorder = &MockMediaURLResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMediaURLResolver) EXPECT() *MockMediaURLResolverMockRecorder {
	return m.recorder
}

// DeleteObject mocks base method.
func (m *MockMediaURLResolver) DeleteObject(ctx context.Context, s3Key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteObject", ctx, s3Key)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteObject indicates an expected call of DeleteObject.
func (mr *MockMediaURLResolverMockRecorder) DeleteObject(ctx, s3Key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteObject", reflect.TypeOf((*MockMediaURLResolver)(nil).DeleteObject), ctx, s3Key)
}

// PresignedUploadURL mocks base method.
func (m *MockMediaURLResolver) PresignedUploadURL(ctx context.Context, s3Key, contentType string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PresignedUploadURL", ctx, s3Key, contentType)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PresignedUploadURL indicates an expected call of PresignedUploadURL.
func (mr *MockMediaURLResolverMockRecorder) PresignedUploadURL(ctx, s3Key, contentType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PresignedUploadURL", reflect.TypeOf((*MockMediaURLResolver)(nil).PresignedUploadURL), ctx, s3Key, contentType)
}

// ReadURL mocks base method.
func (m *MockMediaURLResolver) ReadURL(ctx context.Context, s3Key string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadURL", ctx, s3Key)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadURL indicates an expected call of ReadURL.
func (mr *MockMediaURLResolverMockRecorder) ReadURL(ctx, s3Key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadURL", reflect.TypeOf((*MockMediaURLResolver)(nil).ReadURL), ctx, s3Key)
}

// ReadURLWithTTL mocks base method.
func (m *MockMediaURLResolver) ReadURLWithTTL(ctx context.Context, s3Key string, ttl time.Duration) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadURLWithTTL", ctx, s3Key, ttl)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadURLWithTTL indicates an expected call of ReadURLWithTTL.
func (mr *MockMediaURLResolverMockRecorder) ReadURLWithTTL(ctx, s3Key, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadURLWithTTL", reflect.TypeOf((*MockMediaURLResolver)(nil).ReadURLWithTTL), ctx, s3Key, ttl)
}
