// Code generated by MockGen. DO NOT EDIT.
// Source: pinz/backend/trip-service/internal/repositories (interfaces: PinCreationSessionRepositoryInterface)
//
// Generated by this command:
//
//	mockgen -destination=pin_creation_session_repository_mock.go -package=mocks pinz/backend/trip-service/internal/repositories PinCreationSessionRepositoryInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "pinz/backend/trip-service/internal/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPinCreationSessionRepositoryInterface is a mock of PinCreationSessionRepositoryInterface interface.
type MockPinCreationSessionRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockPinCreationSessionRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockPinCreationSessionRepositoryInterfaceMockRecorder is the mock recorder for MockPinCreationSessionRepositoryInterface.
type MockPinCreationSessionRepositoryInterfaceMockRecorder struct {
	mock *MockPinCreationSessionRepositoryInterface
}

// NewMockPinCreationSessionRepositoryInterface creates a new mock instance.
func NewMockPinCreationSessionRepositoryInterface(ctrl *gomock.Controller) *MockPinCreationSessionRepositoryInterface {
	mock := &MockPinCreationSessionRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockPinCreationSessionRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPinCreationSessionRepositoryInterface) EXPECT() *MockPinCreationSessionRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockPinCreationSessionRepositoryInterface) Close(ctx context.Context, sessionID, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close", ctx, sessionID, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockPinCreationSessionRepositoryInterfaceMockRecorder) Close(ctx, sessionID, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockPinCreationSessionRepositoryInterface)(nil).Close), ctx, sessionID, reason)
}

// Create mocks base method.
func (m *MockPinCreationSessionRepositoryInterface) Create(ctx context.Context, tripID, userID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, tripID, userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPinCreationSessionRepositoryInterfaceMockRecorder) Create(ctx, tripID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPinCreationSessionRepositoryInterface)(nil).Create), ctx, tripID, userID)
}

// GetActiveForTrip mocks base method.
func (m *MockPinCreationSessionRepositoryInterface) GetActiveForTrip(ctx context.Context, tripID string) (*models.PinCreationSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveForTrip", ctx, tripID)
	ret0, _ := ret[0].(*models.PinCreationSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveForTrip indicates an expected call of GetActiveForTrip.
func (mr *MockPinCreationSessionRepositoryInterfaceMockRecorder) GetActiveForTrip(ctx, tripID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveForTrip", reflect.TypeOf((*MockPinCreationSessionRepositoryInterface)(nil).GetActiveForTrip), ctx, tripID)
}

// GetByID mocks base method.
func (m *MockPinCreationSessionRepositoryInterface) GetByID(ctx context.Context, sessionID string) (*models.PinCreationSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, sessionID)
	ret0, _ := ret[0].(*models.PinCreationSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockPinCreationSessionRepositoryInterfaceMockRecorder) GetByID(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockPinCreationSessionRepositoryInterface)(nil).GetByID), ctx, sessionID)
}

// SetDraftSnapshot mocks base method.
func (m *MockPinCreationSessionRepositoryInterface) SetDraftSnapshot(ctx context.Context, sessionID string, snapshot []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDraftSnapshot", ctx, sessionID, snapshot)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetDraftSnapshot indicates an expected call of SetDraftSnapshot.
func (mr *MockPinCreationSessionRepositoryInterfaceMockRecorder) SetDraftSnapshot(ctx, sessionID, snapshot any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDraftSnapshot", reflect.TypeOf((*MockPinCreationSessionRepositoryInterface)(nil).SetDraftSnapshot), ctx, sessionID, snapshot)
}

// Touch mocks base method.
func (m *MockPinCreationSessionRepositoryInterface) Touch(ctx context.Context, sessionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Touch", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Touch indicates an expected call of Touch.
func (mr *MockPinCreationSessionRepositoryInterfaceMockRecorder) Touch(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Touch", reflect.TypeOf((*MockPinCreationSessionRepositoryInterface)(nil).Touch), ctx, sessionID)
}
