// Code generated by MockGen. DO NOT EDIT.
// Source: pinz/backend/trip-service/internal/repositories (interfaces: SocialRepositoryInterface)
//
// Generated by this command:
//
//	mockgen -destination=social_repository_mock.go -package=mocks pinz/backend/trip-service/internal/repositories SocialRepositoryInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSocialRepositoryInterface is a mock of SocialRepositoryInterface interface.
type MockSocialRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockSocialRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockSocialRepositoryInterfaceMockRecorder is the mock recorder for MockSocialRepositoryInterface.
type MockSocialRepositoryInterfaceMockRecorder struct {
	mock *MockSocialRepositoryInterface
}

// NewMockSocialRepositoryInterface creates a new mock instance.
func NewMockSocialRepositoryInterface(ctrl *gomock.Controller) *MockSocialRepositoryInterface {
	mock := &MockSocialRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockSocialRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSocialRepositoryInterface) EXPECT() *MockSocialRepositoryInterfaceMockRecorder {
	return m.recorder
}

// GetReaction mocks base method.
func (m *MockSocialRepositoryInterface) GetReaction(userID, tripID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReaction", userID, tripID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReaction indicates an expected call of GetReaction.
func (mr *MockSocialRepositoryInterfaceMockRecorder) GetReaction(userID, tripID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReaction", reflect.TypeOf((*MockSocialRepositoryInterface)(nil).GetReaction), userID, tripID)
}

// SetReaction mocks base method.
func (m *MockSocialRepositoryInterface) SetReaction(userID, tripID, reaction string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetReaction", userID, tripID, reaction)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetReaction indicates an expected call of SetReaction.
func (mr *MockSocialRepositoryInterfaceMockRecorder) SetReaction(userID, tripID, reaction any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetReaction", reflect.TypeOf((*MockSocialRepositoryInterface)(nil).SetReaction), userID, tripID, reaction)
}
