// Code generated by MockGen. DO NOT EDIT.
// Source: pinz/backend/trip-service/internal/repositories (interfaces: TripRepositoryInterface)
//
// Generated by this command:
//
//	mockgen -destination=trip_repository_mock.go -package=mocks pinz/backend/trip-service/internal/repositories TripRepositoryInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	models "pinz/backend/trip-service/internal/models"
	repositories "pinz/backend/trip-service/internal/repositories"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockTripRepositoryInterface is a mock of TripRepositoryInterface interface.
type MockTripRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockTripRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockTripRepositoryInterfaceMockRecorder is the mock recorder for MockTripRepositoryInterface.
type MockTripRepositoryInterfaceMockRecorder struct {
	mock *MockTripRepositoryInterface
}

// NewMockTripRepositoryInterface creates a new mock instance.
func NewMockTripRepositoryInterface(ctrl *gomock.Controller) *MockTripRepositoryInterface {
	mock := &MockTripRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockTripRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTripRepositoryInterface) EXPECT() *MockTripRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTripRepositoryInterface) Create(t *models.Trip) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", t)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTripRepositoryInterfaceMockRecorder) Create(t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTripRepositoryInterface)(nil).Create), t)
}

// Delete mocks base method.
func (m *MockTripRepositoryInterface) Delete(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTripRepositoryInterfaceMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTripRepositoryInterface)(nil).Delete), id)
}

// GetByID mocks base method.
func (m *MockTripRepositoryInterface) GetByID(id string) (*models.Trip, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*models.Trip)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockTripRepositoryInterfaceMockRecorder) GetByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockTripRepositoryInterface)(nil).GetByID), id)
}

// ListAbandonedGenerated mocks base method.
func (m *MockTripRepositoryInterface) ListAbandonedGenerated(minAge time.Duration, limit int) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAbandonedGenerated", minAge, limit)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAbandonedGenerated indicates an expected call of ListAbandonedGenerated.
func (mr *MockTripRepositoryInterfaceMockRecorder) ListAbandonedGenerated(minAge, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAbandonedGenerated", reflect.TypeOf((*MockTripRepositoryInterface)(nil).ListAbandonedGenerated), minAge, limit)
}

// ListAnniversaryCandidates mocks base method.
func (m *MockTripRepositoryInterface) ListAnniversaryCandidates(today int64) ([]*repositories.NotificationTripCandidate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAnniversaryCandidates", today)
	ret0, _ := ret[0].([]*repositories.NotificationTripCandidate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAnniversaryCandidates indicates an expected call of ListAnniversaryCandidates.
func (mr *MockTripRepositoryInterfaceMockRecorder) ListAnniversaryCandidates(today any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAnniversaryCandidates", reflect.TypeOf((*MockTripRepositoryInterface)(nil).ListAnniversaryCandidates), today)
}

// ListByUserID mocks base method.
func (m *MockTripRepositoryInterface) ListByUserID(userID string, limit, offset int32) ([]*models.Trip, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUserID", userID, limit, offset)
	ret0, _ := ret[0].([]*models.Trip)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUserID indicates an expected call of ListByUserID.
func (mr *MockTripRepositoryInterfaceMockRecorder) ListByUserID(userID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUserID", reflect.TypeOf((*MockTripRepositoryInterface)(nil).ListByUserID), userID, limit, offset)
}

// ListEndedMonthAgoCandidates mocks base method.
func (m *MockTripRepositoryInterface) ListEndedMonthAgoCandidates(today int64) ([]*repositories.NotificationTripCandidate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEndedMonthAgoCandidates", today)
	ret0, _ := ret[0].([]*repositories.NotificationTripCandidate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEndedMonthAgoCandidates indicates an expected call of ListEndedMonthAgoCandidates.
func (mr *MockTripRepositoryInterfaceMockRecorder) ListEndedMonthAgoCandidates(today any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEndedMonthAgoCandidates", reflect.TypeOf((*MockTripRepositoryInterface)(nil).ListEndedMonthAgoCandidates), today)
}

// ListFeed mocks base method.
func (m *MockTripRepositoryInterface) ListFeed(limit, offset int32, category, season string, locationIDs []int, sortBy string) ([]*models.Trip, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFeed", limit, offset, category, season, locationIDs, sortBy)
	ret0, _ := ret[0].([]*models.Trip)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFeed indicates an expected call of ListFeed.
func (mr *MockTripRepositoryInterfaceMockRecorder) ListFeed(limit, offset, category, season, locationIDs, sortBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFeed", reflect.TypeOf((*MockTripRepositoryInterface)(nil).ListFeed), limit, offset, category, season, locationIDs, sortBy)
}

// ListSummariesByUserID mocks base method.
func (m *MockTripRepositoryInterface) ListSummariesByUserID(userID string) ([]*repositories.TripSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSummariesByUserID", userID)
	ret0, _ := ret[0].([]*repositories.TripSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSummariesByUserID indicates an expected call of ListSummariesByUserID.
func (mr *MockTripRepositoryInterfaceMockRecorder) ListSummariesByUserID(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSummariesByUserID", reflect.TypeOf((*MockTripRepositoryInterface)(nil).ListSummariesByUserID), userID)
}

// SetPrivacyLevel mocks base method.
func (m *MockTripRepositoryInterface) SetPrivacyLevel(tripID, level string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPrivacyLevel", tripID, level)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetPrivacyLevel indicates an expected call of SetPrivacyLevel.
func (mr *MockTripRepositoryInterfaceMockRecorder) SetPrivacyLevel(tripID, level any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPrivacyLevel", reflect.TypeOf((*MockTripRepositoryInterface)(nil).SetPrivacyLevel), tripID, level)
}

// SetSoftDeleted mocks base method.
func (m *MockTripRepositoryInterface) SetSoftDeleted(tripID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetSoftDeleted", tripID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetSoftDeleted indicates an expected call of SetSoftDeleted.
func (mr *MockTripRepositoryInterfaceMockRecorder) SetSoftDeleted(tripID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSoftDeleted", reflect.TypeOf((*MockTripRepositoryInterface)(nil).SetSoftDeleted), tripID)
}

// SetStatus mocks base method.
func (m *MockTripRepositoryInterface) SetStatus(tripID, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetStatus", tripID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetStatus indicates an expected call of SetStatus.
func (mr *MockTripRepositoryInterfaceMockRecorder) SetStatus(tripID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStatus", reflect.TypeOf((*MockTripRepositoryInterface)(nil).SetStatus), tripID, status)
}

// Update mocks base method.
func (m *MockTripRepositoryInterface) Update(t *models.Trip) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", t)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockTripRepositoryInterfaceMockRecorder) Update(t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTripRepositoryInterface)(nil).Update), t)
}

// UpdateCoverURL mocks base method.
func (m *MockTripRepositoryInterface) UpdateCoverURL(tripID, s3Key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCoverURL", tripID, s3Key)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCoverURL indicates an expected call of UpdateCoverURL.
func (mr *MockTripRepositoryInterfaceMockRecorder) UpdateCoverURL(tripID, s3Key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCoverURL", reflect.TypeOf((*MockTripRepositoryInterface)(nil).UpdateCoverURL), tripID, s3Key)
}
