// Code generated by MockGen. DO NOT EDIT.
// Source: pinz/backend/trip-service/internal/repositories (interfaces: TripEventPublisher)
//
// Generated by this command:
//
//	mockgen -destination=trip_event_publisher_mock.go -package=mocks pinz/backend/trip-service/internal/repositories TripEventPublisher
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockTripEventPublisher is a mock of TripEventPublisher interface.
type MockTripEventPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockTripEventPublisherMockRecorder
	isgomock struct{}
}

// MockTripEventPublisherMockRecorder is the mock recorder for MockTripEventPublisher.
type MockTripEventPublisherMockRecorder struct {
	mock *MockTripEventPublisher
}

// NewMockTripEventPublisher creates a new mock instance.
func NewMockTripEventPublisher(ctrl *gomock.Controller) *MockTripEventPublisher {
	mock := &MockTripEventPublisher{ctrl: ctrl}
	mock.recorder = &MockTripEventPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTripEventPublisher) EXPECT() *MockTripEventPublisherMockRecorder {
	return m.recorder
}

// AddMLTask mocks base method.
func (m *MockTripEventPublisher) AddMLTask(ctx context.Context, tripID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMLTask", ctx, tripID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddMLTask indicates an expected call of AddMLTask.
func (mr *MockTripEventPublisherMockRecorder) AddMLTask(ctx, tripID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMLTask", reflect.TypeOf((*MockTripEventPublisher)(nil).AddMLTask), ctx, tripID)
}

// AddMLTaskWithFlow mocks base method.
func (m *MockTripEventPublisher) AddMLTaskWithFlow(ctx context.Context, tripID, flow string, newPinIDs []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMLTaskWithFlow", ctx, tripID, flow, newPinIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddMLTaskWithFlow indicates an expected call of AddMLTaskWithFlow.
func (mr *MockTripEventPublisherMockRecorder) AddMLTaskWithFlow(ctx, tripID, flow, newPinIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMLTaskWithFlow", reflect.TypeOf((*MockTripEventPublisher)(nil).AddMLTaskWithFlow), ctx, tripID, flow, newPinIDs)
}

// DeleteTripEventStream mocks base method.
func (m *MockTripEventPublisher) DeleteTripEventStream(ctx context.Context, tripID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTripEventStream", ctx, tripID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTripEventStream indicates an expected call of DeleteTripEventStream.
func (mr *MockTripEventPublisherMockRecorder) DeleteTripEventStream(ctx, tripID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTripEventStream", reflect.TypeOf((*MockTripEventPublisher)(nil).DeleteTripEventStream), ctx, tripID)
}

// PublishPrivacyEvent mocks base method.
func (m *MockTripEventPublisher) PublishPrivacyEvent(ctx context.Context, objectType, objectID, tripID, userID, privacyLevel string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishPrivacyEvent", ctx, objectType, objectID, tripID, userID, privacyLevel)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishPrivacyEvent indicates an expected call of PublishPrivacyEvent.
func (mr *MockTripEventPublisherMockRecorder) PublishPrivacyEvent(ctx, objectType, objectID, tripID, userID, privacyLevel any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishPrivacyEvent", reflect.TypeOf((*MockTripEventPublisher)(nil).PublishPrivacyEvent), ctx, objectType, objectID, tripID, userID, privacyLevel)
}

// PublishStatsEvent mocks base method.
func (m *MockTripEventPublisher) PublishStatsEvent(ctx context.Context, eventType, tripID string, userIDs []string, payload map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishStatsEvent", ctx, eventType, tripID, userIDs, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishStatsEvent indicates an expected call of PublishStatsEvent.
func (mr *MockTripEventPublisherMockRecorder) PublishStatsEvent(ctx, eventType, tripID, userIDs, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishStatsEvent", reflect.TypeOf((*MockTripEventPublisher)(nil).PublishStatsEvent), ctx, eventType, tripID, userIDs, payload)
}

// PublishTripEvent mocks base method.
func (m *MockTripEventPublisher) PublishTripEvent(ctx context.Context, eventType, tripID, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishTripEvent", ctx, eventType, tripID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishTripEvent indicates an expected call of PublishTripEvent.
func (mr *MockTripEventPublisherMockRecorder) PublishTripEvent(ctx, eventType, tripID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishTripEvent", reflect.TypeOf((*MockTripEventPublisher)(nil).PublishTripEvent), ctx, eventType, tripID, userID)
}

// PublishTripEventWS mocks base method.
func (m *MockTripEventPublisher) PublishTripEventWS(ctx context.Context, tripID string, userIDs []string, eventType string, payload map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishTripEventWS", ctx, tripID, userIDs, eventType, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishTripEventWS indicates an expected call of PublishTripEventWS.
func (mr *MockTripEventPublisherMockRecorder) PublishTripEventWS(ctx, tripID, userIDs, eventType, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishTripEventWS", reflect.TypeOf((*MockTripEventPublisher)(nil).PublishTripEventWS), ctx, tripID, userIDs, eventType, payload)
}

// SetMLContext mocks base method.
func (m *MockTripEventPublisher) SetMLContext(ctx context.Context, tripID, flow string, newPinIDs []string, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetMLContext", ctx, tripID, flow, newPinIDs, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetMLContext indicates an expected call of SetMLContext.
func (mr *MockTripEventPublisherMockRecorder) SetMLContext(ctx, tripID, flow, newPinIDs, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMLContext", reflect.TypeOf((*MockTripEventPublisher)(nil).SetMLContext), ctx, tripID, flow, newPinIDs, ttl)
}
