// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: desired_places.sql

package sqlcdb

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const clearDesiredPlaceImage = `-- name: ClearDesiredPlaceImage :one
UPDATE desired_places
SET image_url = NULL
WHERE id = $1
RETURNING id, user_id, name, description, image_url, created_at
`

func (q *Queries) ClearDesiredPlaceImage(ctx context.Context, id uuid.UUID) (DesiredPlace, error) {
	row := q.db.QueryRowContext(ctx, clearDesiredPlaceImage, id)
	var i DesiredPlace
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.ImageUrl,
		&i.CreatedAt,
	)
	return i, err
}

const createDesiredPlace = `-- name: CreateDesiredPlace :one
INSERT INTO desired_places (id, user_id, name, description, image_url)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, name, description, image_url, created_at
`

type CreateDesiredPlaceParams struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Name        string
	Description string
	ImageUrl    sql.NullString
}

func (q *Queries) CreateDesiredPlace(ctx context.Context, arg CreateDesiredPlaceParams) (DesiredPlace, error) {
	row := q.db.QueryRowContext(ctx, createDesiredPlace,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.ImageUrl,
	)
	var i DesiredPlace
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.ImageUrl,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDesiredPlace = `-- name: DeleteDesiredPlace :exec
DELETE FROM desired_places WHERE id = $1
`

func (q *Queries) DeleteDesiredPlace(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteDesiredPlace, id)
	return err
}

const getDesiredPlace = `-- name: GetDesiredPlace :one
SELECT id, user_id, name, description, image_url, created_at
FROM desired_places
WHERE id = $1
`

func (q *Queries) GetDesiredPlace(ctx context.Context, id uuid.UUID) (DesiredPlace, error) {
	row := q.db.QueryRowContext(ctx, getDesiredPlace, id)
	var i DesiredPlace
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.ImageUrl,
		&i.CreatedAt,
	)
	return i, err
}

const listDesiredPlacesByUserID = `-- name: ListDesiredPlacesByUserID :many
SELECT id, user_id, name, description, image_url, created_at
FROM desired_places
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListDesiredPlacesByUserID(ctx context.Context, userID uuid.UUID) ([]DesiredPlace, error) {
	rows, err := q.db.QueryContext(ctx, listDesiredPlacesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DesiredPlace{}
	for rows.Next() {
		var i DesiredPlace
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.ImageUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDesiredPlace = `-- name: UpdateDesiredPlace :one
UPDATE desired_places
SET name = $2,
    description = $3,
    image_url = $4
WHERE id = $1
RETURNING id, user_id, name, description, image_url, created_at
`

type UpdateDesiredPlaceParams struct {
	ID          uuid.UUID
	Name        string
	Description string
	ImageUrl    sql.NullString
}

func (q *Queries) UpdateDesiredPlace(ctx context.Context, arg UpdateDesiredPlaceParams) (DesiredPlace, error) {
	row := q.db.QueryRowContext(ctx, updateDesiredPlace,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.ImageUrl,
	)
	var i DesiredPlace
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.ImageUrl,
		&i.CreatedAt,
	)
	return i, err
}

const updateDesiredPlaceContent = `-- name: UpdateDesiredPlaceContent :one
UPDATE desired_places
SET name = $2,
    description = $3
WHERE id = $1
RETURNING id, user_id, name, description, image_url, created_at
`

type UpdateDesiredPlaceContentParams struct {
	ID          uuid.UUID
	Name        string
	Description string
}

func (q *Queries) UpdateDesiredPlaceContent(ctx context.Context, arg UpdateDesiredPlaceContentParams) (DesiredPlace, error) {
	row := q.db.QueryRowContext(ctx, updateDesiredPlaceContent, arg.ID, arg.Name, arg.Description)
	var i DesiredPlace
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.ImageUrl,
		&i.CreatedAt,
	)
	return i, err
}
