// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlcdb

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type PasskeyCredential struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	CredentialID   []byte
	CredentialJson json.RawMessage
	CreatedAt      time.Time
}

type RefreshToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Token     string
	ExpiresAt time.Time
}

type User struct {
	ID        uuid.UUID
	Email     string
	Username  string
	AvatarUrl sql.NullString
	CreatedAt time.Time
}
