replicaCount: 1

image:
  repository: ghcr.io/dmitry-pr/pinz-auth-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  name: grpc
  port: 50051

env:
  dbHost: db
  dbPort: "5432"
  dbUser: pinz_user
  dbName: pinz_db
  redisAddr: redis:6379
  grpcPort: ":50051"

secret:
  dbPassword: "REPLACE_IN_PRODUCTION"
  jwtSecretKey: "REPLACE_IN_PRODUCTION"

resources:
  requests:
    cpu: "50m"
    memory: "64Mi"
  limits:
    cpu: "200m"
    memory: "128Mi"

pdb:
  enabled: false
  minAvailable: 1

dockerConfig:
  auths:
    ghcr.io:
      username: "{{ .Values.github.actor }}"
      password: "{{ .Values.github.token }}"
