apiVersion: v1
kind: ConfigMap
metadata:
  name: nats-config
  labels:
    app: nats
data:
  nats-server.conf: |
    server_name: nats-pinz
    listen: 0.0.0.0:{{ .Values.service.clientPort }}
    http: 0.0.0.0:{{ .Values.service.monitorPort }}

    jetstream {
      store_dir: "/data/jetstream"
      max_memory_store: {{ .Values.jetstream.maxMemoryStore }}
      max_file_store: {{ .Values.jetstream.maxFileStore }}
    }

    websocket {
      port: {{ .Values.service.websocketPort }}
      no_tls: true
      compression: true
    }

    include "auth.conf"
