apiVersion: v1
kind: Service
metadata:
  name: nats
  labels:
    app: nats
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.service.monitorPort }}"
    prometheus.io/path: "/varz"
spec:
  selector:
    app: nats
  ports:
    - name: tcp-client
      port: {{ .Values.service.clientPort }}
      targetPort: client
      appProtocol: tcp
    - name: tcp-monitor
      port: {{ .Values.service.monitorPort }}
      targetPort: monitor
      appProtocol: tcp
    - name: http-websocket
      port: {{ .Values.service.websocketPort }}
      targetPort: websocket
      appProtocol: http
  type: ClusterIP
