// Code generated by MockGen. DO NOT EDIT.
// Source: pinz/backend/notification-service/internal/apns (interfaces: Sender)
//
// Generated by this command:
//
//	mockgen -destination=apns_sender_mock.go -package=mocks pinz/backend/notification-service/internal/apns Sender
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "pinz/backend/notification-service/internal/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSender is a mock of Sender interface.
type MockSender struct {
	ctrl     *gomock.Controller
	recorder *MockSenderMockRecorder
	isgomock struct{}
}

// MockSenderMockRecorder is the mock recorder for MockSender.
type MockSenderMockRecorder struct {
	mock *MockSender
}

// NewMockSender creates a new mock instance.
func NewMockSender(ctrl *gomock.Controller) *MockSender {
	mock := &MockSender{ctrl: ctrl}
	mock.recorder = &MockSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSender) EXPECT() *MockSenderMockRecorder {
	return m.recorder
}

// Send mocks base method.
func (m *MockSender) Send(ctx context.Context, apnsToken string, n models.PushNotification) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, apnsToken, n)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockSenderMockRecorder) Send(ctx, apnsToken, n any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockSender)(nil).Send), ctx, apnsToken, n)
}
