// Code generated by MockGen. DO NOT EDIT.
// Source: pinz/backend/notification-service/internal/repositories (interfaces: DeviceTokensRepositoryInterface)
//
// Generated by this command:
//
//	mockgen -destination=device_tokens_repository_mock.go -package=mocks pinz/backend/notification-service/internal/repositories DeviceTokensRepositoryInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "pinz/backend/notification-service/internal/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDeviceTokensRepositoryInterface is a mock of DeviceTokensRepositoryInterface interface.
type MockDeviceTokensRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockDeviceTokensRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockDeviceTokensRepositoryInterfaceMockRecorder is the mock recorder for MockDeviceTokensRepositoryInterface.
type MockDeviceTokensRepositoryInterfaceMockRecorder struct {
	mock *MockDeviceTokensRepositoryInterface
}

// NewMockDeviceTokensRepositoryInterface creates a new mock instance.
func NewMockDeviceTokensRepositoryInterface(ctrl *gomock.Controller) *MockDeviceTokensRepositoryInterface {
	mock := &MockDeviceTokensRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockDeviceTokensRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeviceTokensRepositoryInterface) EXPECT() *MockDeviceTokensRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockDeviceTokensRepositoryInterface) Delete(ctx context.Context, userID, apnsToken string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, userID, apnsToken)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockDeviceTokensRepositoryInterfaceMockRecorder) Delete(ctx, userID, apnsToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDeviceTokensRepositoryInterface)(nil).Delete), ctx, userID, apnsToken)
}

// DeleteByToken mocks base method.
func (m *MockDeviceTokensRepositoryInterface) DeleteByToken(ctx context.Context, apnsToken string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByToken", ctx, apnsToken)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteByToken indicates an expected call of DeleteByToken.
func (mr *MockDeviceTokensRepositoryInterfaceMockRecorder) DeleteByToken(ctx, apnsToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByToken", reflect.TypeOf((*MockDeviceTokensRepositoryInterface)(nil).DeleteByToken), ctx, apnsToken)
}

// ListByUser mocks base method.
func (m *MockDeviceTokensRepositoryInterface) ListByUser(ctx context.Context, userID string) ([]models.DeviceToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUser", ctx, userID)
	ret0, _ := ret[0].([]models.DeviceToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUser indicates an expected call of ListByUser.
func (mr *MockDeviceTokensRepositoryInterfaceMockRecorder) ListByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUser", reflect.TypeOf((*MockDeviceTokensRepositoryInterface)(nil).ListByUser), ctx, userID)
}

// ListByUsers mocks base method.
func (m *MockDeviceTokensRepositoryInterface) ListByUsers(ctx context.Context, userIDs []string) ([]models.DeviceToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUsers", ctx, userIDs)
	ret0, _ := ret[0].([]models.DeviceToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUsers indicates an expected call of ListByUsers.
func (mr *MockDeviceTokensRepositoryInterfaceMockRecorder) ListByUsers(ctx, userIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUsers", reflect.TypeOf((*MockDeviceTokensRepositoryInterface)(nil).ListByUsers), ctx, userIDs)
}

// Upsert mocks base method.
func (m *MockDeviceTokensRepositoryInterface) Upsert(ctx context.Context, userID, apnsToken string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, userID, apnsToken)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upsert indicates an expected call of Upsert.
func (mr *MockDeviceTokensRepositoryInterfaceMockRecorder) Upsert(ctx, userID, apnsToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockDeviceTokensRepositoryInterface)(nil).Upsert), ctx, userID, apnsToken)
}
