// Code generated by MockGen. DO NOT EDIT.
// Source: pinz/backend/notification-service/internal/repositories (interfaces: TripClientInterface)
//
// Generated by this command:
//
//	mockgen -destination=trip_client_mock.go -package=mocks pinz/backend/notification-service/internal/repositories TripClientInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	proto "pinz/backend/notification-service/pkg/proto"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTripClientInterface is a mock of TripClientInterface interface.
type MockTripClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockTripClientInterfaceMockRecorder
	isgomock struct{}
}

// MockTripClientInterfaceMockRecorder is the mock recorder for MockTripClientInterface.
type MockTripClientInterfaceMockRecorder struct {
	mock *MockTripClientInterface
}

// NewMockTripClientInterface creates a new mock instance.
func NewMockTripClientInterface(ctrl *gomock.Controller) *MockTripClientInterface {
	mock := &MockTripClientInterface{ctrl: ctrl}
	mock.recorder = &MockTripClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTripClientInterface) EXPECT() *MockTripClientInterfaceMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockTripClientInterface) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockTripClientInterfaceMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockTripClientInterface)(nil).Close))
}

// GetNotificationSettings mocks base method.
func (m *MockTripClientInterface) GetNotificationSettings(ctx context.Context, tripID string, userIDs []string) (map[string]bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNotificationSettings", ctx, tripID, userIDs)
	ret0, _ := ret[0].(map[string]bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNotificationSettings indicates an expected call of GetNotificationSettings.
func (mr *MockTripClientInterfaceMockRecorder) GetNotificationSettings(ctx, tripID, userIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNotificationSettings", reflect.TypeOf((*MockTripClientInterface)(nil).GetNotificationSettings), ctx, tripID, userIDs)
}

// ListAnniversaryTrips mocks base method.
func (m *MockTripClientInterface) ListAnniversaryTrips(ctx context.Context, todayUnix int64) ([]*proto.NotificationTrip, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAnniversaryTrips", ctx, todayUnix)
	ret0, _ := ret[0].([]*proto.NotificationTrip)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAnniversaryTrips indicates an expected call of ListAnniversaryTrips.
func (mr *MockTripClientInterfaceMockRecorder) ListAnniversaryTrips(ctx, todayUnix any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAnniversaryTrips", reflect.TypeOf((*MockTripClientInterface)(nil).ListAnniversaryTrips), ctx, todayUnix)
}

// ListEndedMonthAgoTrips mocks base method.
func (m *MockTripClientInterface) ListEndedMonthAgoTrips(ctx context.Context, todayUnix int64) ([]*proto.NotificationTrip, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEndedMonthAgoTrips", ctx, todayUnix)
	ret0, _ := ret[0].([]*proto.NotificationTrip)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEndedMonthAgoTrips indicates an expected call of ListEndedMonthAgoTrips.
func (mr *MockTripClientInterfaceMockRecorder) ListEndedMonthAgoTrips(ctx, todayUnix any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEndedMonthAgoTrips", reflect.TypeOf((*MockTripClientInterface)(nil).ListEndedMonthAgoTrips), ctx, todayUnix)
}

// ListTripParticipantIDs mocks base method.
func (m *MockTripClientInterface) ListTripParticipantIDs(ctx context.Context, tripID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTripParticipantIDs", ctx, tripID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTripParticipantIDs indicates an expected call of ListTripParticipantIDs.
func (mr *MockTripClientInterfaceMockRecorder) ListTripParticipantIDs(ctx, tripID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTripParticipantIDs", reflect.TypeOf((*MockTripClientInterface)(nil).ListTripParticipantIDs), ctx, tripID)
}
