// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlcdb

import (
	"time"

	"github.com/google/uuid"
)

type DeviceToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	ApnsToken string
	UpdatedAt time.Time
}

type NotificationLog struct {
	EventID   string
	ApnsToken string
	SentAt    time.Time
}
