// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: notification_log.sql

package sqlcdb

import (
	"context"
)

const notificationLogExists = `-- name: NotificationLogExists :one
SELECT EXISTS(
 SELECT 1 FROM notification_log WHERE event_id = $1 AND apns_token = $2
)
`

type NotificationLogExistsParams struct {
	EventID   string
	ApnsToken string
}

func (q *Queries) NotificationLogExists(ctx context.Context, arg NotificationLogExistsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, notificationLogExists, arg.EventID, arg.ApnsToken)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const notificationLogInsert = `-- name: NotificationLogInsert :execrows
INSERT INTO notification_log (event_id, apns_token)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type NotificationLogInsertParams struct {
	EventID   string
	ApnsToken string
}

// Записывает факт отправки пуша. Уникальный ключ (event_id, apns_token)
// обеспечивает идемпотентность: повторная попытка получит 0 rows.
func (q *Queries) NotificationLogInsert(ctx context.Context, arg NotificationLogInsertParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, notificationLogInsert, arg.EventID, arg.ApnsToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
