// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: trip.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TripService_CreateTrip_FullMethodName                    = "/trip.TripService/CreateTrip"
	TripService_GetTrip_FullMethodName                       = "/trip.TripService/GetTrip"
	TripService_ListUserTrips_FullMethodName                 = "/trip.TripService/ListUserTrips"
	TripService_UpdateTrip_FullMethodName                    = "/trip.TripService/UpdateTrip"
	TripService_DeleteTrip_FullMethodName                    = "/trip.TripService/DeleteTrip"
	TripService_RequestTripCoverUpload_FullMethodName        = "/trip.TripService/RequestTripCoverUpload"
	TripService_ConfirmTripCoverUpload_FullMethodName        = "/trip.TripService/ConfirmTripCoverUpload"
	TripService_DeleteTripCover_FullMethodName               = "/trip.TripService/DeleteTripCover"
	TripService_GenerateInviteLink_FullMethodName            = "/trip.TripService/GenerateInviteLink"
	TripService_JoinTripByToken_FullMethodName               = "/trip.TripService/JoinTripByToken"
	TripService_RemoveParticipant_FullMethodName             = "/trip.TripService/RemoveParticipant"
	TripService_LeaveTrip_FullMethodName                     = "/trip.TripService/LeaveTrip"
	TripService_TransferAdmin_FullMethodName                 = "/trip.TripService/TransferAdmin"
	TripService_ProcessMediaGrouping_FullMethodName          = "/trip.TripService/ProcessMediaGrouping"
	TripService_ApplyGroupsAndProcess_FullMethodName         = "/trip.TripService/ApplyGroupsAndProcess"
	TripService_GetTripReview_FullMethodName                 = "/trip.TripService/GetTripReview"
	TripService_FinalizeTrip_FullMethodName                  = "/trip.TripService/FinalizeTrip"
	TripService_PublishTrip_FullMethodName                   = "/trip.TripService/PublishTrip"
	TripService_UpdateTripSettings_FullMethodName            = "/trip.TripService/UpdateTripSettings"
	TripService_ListFeed_FullMethodName                      = "/trip.TripService/ListFeed"
	TripService_LikeTrip_FullMethodName                      = "/trip.TripService/LikeTrip"
	TripService_DislikeTrip_FullMethodName                   = "/trip.TripService/DislikeTrip"
	TripService_AddToFavourites_FullMethodName               = "/trip.TripService/AddToFavourites"
	TripService_RemoveFromFavourites_FullMethodName          = "/trip.TripService/RemoveFromFavourites"
	TripService_ListFavourites_FullMethodName                = "/trip.TripService/ListFavourites"
	TripService_AddMediaStart_FullMethodName                 = "/trip.TripService/AddMediaStart"
	TripService_AddMediaProcessGrouping_FullMethodName       = "/trip.TripService/AddMediaProcessGrouping"
	TripService_AddMediaApplyGroupsAndProcess_FullMethodName = "/trip.TripService/AddMediaApplyGroupsAndProcess"
)

// TripServiceClient is the client API for TripService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TripServiceClient interface {
	CreateTrip(ctx context.Context, in *CreateTripRequest, opts ...grpc.CallOption) (*CreateTripResponse, error)
	GetTrip(ctx context.Context, in *GetTripRequest, opts ...grpc.CallOption) (*GetTripResponse, error)
	ListUserTrips(ctx context.Context, in *ListUserTripsRequest, opts ...grpc.CallOption) (*ListUserTripsResponse, error)
	UpdateTrip(ctx context.Context, in *UpdateTripRequest, opts ...grpc.CallOption) (*UpdateTripResponse, error)
	DeleteTrip(ctx context.Context, in *DeleteTripRequest, opts ...grpc.CallOption) (*DeleteTripResponse, error)
	// Обложка трипа (двухшаговый поток, аналогичный аватару пользователя)
	RequestTripCoverUpload(ctx context.Context, in *RequestTripCoverUploadRequest, opts ...grpc.CallOption) (*RequestTripCoverUploadResponse, error)
	ConfirmTripCoverUpload(ctx context.Context, in *ConfirmTripCoverUploadRequest, opts ...grpc.CallOption) (*ConfirmTripCoverUploadResponse, error)
	DeleteTripCover(ctx context.Context, in *DeleteTripCoverRequest, opts ...grpc.CallOption) (*DeleteTripCoverResponse, error)
	// Участники и инвайты (Фаза 2)
	GenerateInviteLink(ctx context.Context, in *GenerateInviteLinkRequest, opts ...grpc.CallOption) (*GenerateInviteLinkResponse, error)
	JoinTripByToken(ctx context.Context, in *JoinTripByTokenRequest, opts ...grpc.CallOption) (*JoinTripByTokenResponse, error)
	RemoveParticipant(ctx context.Context, in *RemoveParticipantRequest, opts ...grpc.CallOption) (*RemoveParticipantResponse, error)
	LeaveTrip(ctx context.Context, in *LeaveTripRequest, opts ...grpc.CallOption) (*LeaveTripResponse, error)
	TransferAdmin(ctx context.Context, in *TransferAdminRequest, opts ...grpc.CallOption) (*TransferAdminResponse, error)
	// Поток создания (tripCreationFlow.md), Фаза 3/5:
	ProcessMediaGrouping(ctx context.Context, in *ProcessMediaGroupingRequest, opts ...grpc.CallOption) (*ProcessMediaGroupingResponse, error)
	ApplyGroupsAndProcess(ctx context.Context, in *ApplyGroupsAndProcessRequest, opts ...grpc.CallOption) (*ApplyGroupsAndProcessResponse, error)
	GetTripReview(ctx context.Context, in *GetTripReviewRequest, opts ...grpc.CallOption) (*GetTripReviewResponse, error)
	FinalizeTrip(ctx context.Context, in *FinalizeTripRequest, opts ...grpc.CallOption) (*FinalizeTripResponse, error)
	// Публикация в ленту (PINZ-105, ТЗ 3.3): вся поездка целиком или выбранные пины
	PublishTrip(ctx context.Context, in *PublishTripRequest, opts ...grpc.CallOption) (*PublishTripResponse, error)
	// PINZ-98: лента, лайки, избранное, настройки уведомлений
	UpdateTripSettings(ctx context.Context, in *UpdateTripSettingsRequest, opts ...grpc.CallOption) (*UpdateTripSettingsResponse, error)
	ListFeed(ctx context.Context, in *ListFeedRequest, opts ...grpc.CallOption) (*ListFeedResponse, error)
	LikeTrip(ctx context.Context, in *LikeTripRequest, opts ...grpc.CallOption) (*LikeTripResponse, error)
	DislikeTrip(ctx context.Context, in *DislikeTripRequest, opts ...grpc.CallOption) (*DislikeTripResponse, error)
	AddToFavourites(ctx context.Context, in *AddToFavouritesRequest, opts ...grpc.CallOption) (*AddToFavouritesResponse, error)
	RemoveFromFavourites(ctx context.Context, in *RemoveFromFavouritesRequest, opts ...grpc.CallOption) (*RemoveFromFavouritesResponse, error)
	ListFavourites(ctx context.Context, in *ListFavouritesRequest, opts ...grpc.CallOption) (*ListFavouritesResponse, error)
	// PINZ-131: Добавление медиа в существующий трип (ТЗ 5.1-5.3)
	AddMediaStart(ctx context.Context, in *AddMediaStartRequest, opts ...grpc.CallOption) (*AddMediaStartResponse, error)
	AddMediaProcessGrouping(ctx context.Context, in *AddMediaProcessGroupingRequest, opts ...grpc.CallOption) (*AddMediaProcessGroupingResponse, error)
	AddMediaApplyGroupsAndProcess(ctx context.Context, in *AddMediaApplyGroupsAndProcessRequest, opts ...grpc.CallOption) (*AddMediaApplyGroupsAndProcessResponse, error)
}

type tripServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTripServiceClient(cc grpc.ClientConnInterface) TripServiceClient {
	return &tripServiceClient{cc}
}

func (c *tripServiceClient) CreateTrip(ctx context.Context, in *CreateTripRequest, opts ...grpc.CallOption) (*CreateTripResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTripResponse)
	err := c.cc.Invoke(ctx, TripService_CreateTrip_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) GetTrip(ctx context.Context, in *GetTripRequest, opts ...grpc.CallOption) (*GetTripResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTripResponse)
	err := c.cc.Invoke(ctx, TripService_GetTrip_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) ListUserTrips(ctx context.Context, in *ListUserTripsRequest, opts ...grpc.CallOption) (*ListUserTripsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUserTripsResponse)
	err := c.cc.Invoke(ctx, TripService_ListUserTrips_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) UpdateTrip(ctx context.Context, in *UpdateTripRequest, opts ...grpc.CallOption) (*UpdateTripResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateTripResponse)
	err := c.cc.Invoke(ctx, TripService_UpdateTrip_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) DeleteTrip(ctx context.Context, in *DeleteTripRequest, opts ...grpc.CallOption) (*DeleteTripResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTripResponse)
	err := c.cc.Invoke(ctx, TripService_DeleteTrip_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) RequestTripCoverUpload(ctx context.Context, in *RequestTripCoverUploadRequest, opts ...grpc.CallOption) (*RequestTripCoverUploadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestTripCoverUploadResponse)
	err := c.cc.Invoke(ctx, TripService_RequestTripCoverUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) ConfirmTripCoverUpload(ctx context.Context, in *ConfirmTripCoverUploadRequest, opts ...grpc.CallOption) (*ConfirmTripCoverUploadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfirmTripCoverUploadResponse)
	err := c.cc.Invoke(ctx, TripService_ConfirmTripCoverUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) DeleteTripCover(ctx context.Context, in *DeleteTripCoverRequest, opts ...grpc.CallOption) (*DeleteTripCoverResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTripCoverResponse)
	err := c.cc.Invoke(ctx, TripService_DeleteTripCover_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) GenerateInviteLink(ctx context.Context, in *GenerateInviteLinkRequest, opts ...grpc.CallOption) (*GenerateInviteLinkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateInviteLinkResponse)
	err := c.cc.Invoke(ctx, TripService_GenerateInviteLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) JoinTripByToken(ctx context.Context, in *JoinTripByTokenRequest, opts ...grpc.CallOption) (*JoinTripByTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinTripByTokenResponse)
	err := c.cc.Invoke(ctx, TripService_JoinTripByToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) RemoveParticipant(ctx context.Context, in *RemoveParticipantRequest, opts ...grpc.CallOption) (*RemoveParticipantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveParticipantResponse)
	err := c.cc.Invoke(ctx, TripService_RemoveParticipant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) LeaveTrip(ctx context.Context, in *LeaveTripRequest, opts ...grpc.CallOption) (*LeaveTripResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LeaveTripResponse)
	err := c.cc.Invoke(ctx, TripService_LeaveTrip_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) TransferAdmin(ctx context.Context, in *TransferAdminRequest, opts ...grpc.CallOption) (*TransferAdminResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferAdminResponse)
	err := c.cc.Invoke(ctx, TripService_TransferAdmin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) ProcessMediaGrouping(ctx context.Context, in *ProcessMediaGroupingRequest, opts ...grpc.CallOption) (*ProcessMediaGroupingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessMediaGroupingResponse)
	err := c.cc.Invoke(ctx, TripService_ProcessMediaGrouping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) ApplyGroupsAndProcess(ctx context.Context, in *ApplyGroupsAndProcessRequest, opts ...grpc.CallOption) (*ApplyGroupsAndProcessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyGroupsAndProcessResponse)
	err := c.cc.Invoke(ctx, TripService_ApplyGroupsAndProcess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) GetTripReview(ctx context.Context, in *GetTripReviewRequest, opts ...grpc.CallOption) (*GetTripReviewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTripReviewResponse)
	err := c.cc.Invoke(ctx, TripService_GetTripReview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) FinalizeTrip(ctx context.Context, in *FinalizeTripRequest, opts ...grpc.CallOption) (*FinalizeTripResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FinalizeTripResponse)
	err := c.cc.Invoke(ctx, TripService_FinalizeTrip_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) PublishTrip(ctx context.Context, in *PublishTripRequest, opts ...grpc.CallOption) (*PublishTripResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishTripResponse)
	err := c.cc.Invoke(ctx, TripService_PublishTrip_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) UpdateTripSettings(ctx context.Context, in *UpdateTripSettingsRequest, opts ...grpc.CallOption) (*UpdateTripSettingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateTripSettingsResponse)
	err := c.cc.Invoke(ctx, TripService_UpdateTripSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) ListFeed(ctx context.Context, in *ListFeedRequest, opts ...grpc.CallOption) (*ListFeedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFeedResponse)
	err := c.cc.Invoke(ctx, TripService_ListFeed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) LikeTrip(ctx context.Context, in *LikeTripRequest, opts ...grpc.CallOption) (*LikeTripResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LikeTripResponse)
	err := c.cc.Invoke(ctx, TripService_LikeTrip_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) DislikeTrip(ctx context.Context, in *DislikeTripRequest, opts ...grpc.CallOption) (*DislikeTripResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DislikeTripResponse)
	err := c.cc.Invoke(ctx, TripService_DislikeTrip_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) AddToFavourites(ctx context.Context, in *AddToFavouritesRequest, opts ...grpc.CallOption) (*AddToFavouritesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddToFavouritesResponse)
	err := c.cc.Invoke(ctx, TripService_AddToFavourites_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) RemoveFromFavourites(ctx context.Context, in *RemoveFromFavouritesRequest, opts ...grpc.CallOption) (*RemoveFromFavouritesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveFromFavouritesResponse)
	err := c.cc.Invoke(ctx, TripService_RemoveFromFavourites_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) ListFavourites(ctx context.Context, in *ListFavouritesRequest, opts ...grpc.CallOption) (*ListFavouritesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFavouritesResponse)
	err := c.cc.Invoke(ctx, TripService_ListFavourites_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) AddMediaStart(ctx context.Context, in *AddMediaStartRequest, opts ...grpc.CallOption) (*AddMediaStartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddMediaStartResponse)
	err := c.cc.Invoke(ctx, TripService_AddMediaStart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) AddMediaProcessGrouping(ctx context.Context, in *AddMediaProcessGroupingRequest, opts ...grpc.CallOption) (*AddMediaProcessGroupingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddMediaProcessGroupingResponse)
	err := c.cc.Invoke(ctx, TripService_AddMediaProcessGrouping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) AddMediaApplyGroupsAndProcess(ctx context.Context, in *AddMediaApplyGroupsAndProcessRequest, opts ...grpc.CallOption) (*AddMediaApplyGroupsAndProcessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddMediaApplyGroupsAndProcessResponse)
	err := c.cc.Invoke(ctx, TripService_AddMediaApplyGroupsAndProcess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TripServiceServer is the server API for TripService service.
// All implementations must embed UnimplementedTripServiceServer
// for forward compatibility.
type TripServiceServer interface {
	CreateTrip(context.Context, *CreateTripRequest) (*CreateTripResponse, error)
	GetTrip(context.Context, *GetTripRequest) (*GetTripResponse, error)
	ListUserTrips(context.Context, *ListUserTripsRequest) (*ListUserTripsResponse, error)
	UpdateTrip(context.Context, *UpdateTripRequest) (*UpdateTripResponse, error)
	DeleteTrip(context.Context, *DeleteTripRequest) (*DeleteTripResponse, error)
	// Обложка трипа (двухшаговый поток, аналогичный аватару пользователя)
	RequestTripCoverUpload(context.Context, *RequestTripCoverUploadRequest) (*RequestTripCoverUploadResponse, error)
	ConfirmTripCoverUpload(context.Context, *ConfirmTripCoverUploadRequest) (*ConfirmTripCoverUploadResponse, error)
	DeleteTripCover(context.Context, *DeleteTripCoverRequest) (*DeleteTripCoverResponse, error)
	// Участники и инвайты (Фаза 2)
	GenerateInviteLink(context.Context, *GenerateInviteLinkRequest) (*GenerateInviteLinkResponse, error)
	JoinTripByToken(context.Context, *JoinTripByTokenRequest) (*JoinTripByTokenResponse, error)
	RemoveParticipant(context.Context, *RemoveParticipantRequest) (*RemoveParticipantResponse, error)
	LeaveTrip(context.Context, *LeaveTripRequest) (*LeaveTripResponse, error)
	TransferAdmin(context.Context, *TransferAdminRequest) (*TransferAdminResponse, error)
	// Поток создания (tripCreationFlow.md), Фаза 3/5:
	ProcessMediaGrouping(context.Context, *ProcessMediaGroupingRequest) (*ProcessMediaGroupingResponse, error)
	ApplyGroupsAndProcess(context.Context, *ApplyGroupsAndProcessRequest) (*ApplyGroupsAndProcessResponse, error)
	GetTripReview(context.Context, *GetTripReviewRequest) (*GetTripReviewResponse, error)
	FinalizeTrip(context.Context, *FinalizeTripRequest) (*FinalizeTripResponse, error)
	// Публикация в ленту (PINZ-105, ТЗ 3.3): вся поездка целиком или выбранные пины
	PublishTrip(context.Context, *PublishTripRequest) (*PublishTripResponse, error)
	// PINZ-98: лента, лайки, избранное, настройки уведомлений
	UpdateTripSettings(context.Context, *UpdateTripSettingsRequest) (*UpdateTripSettingsResponse, error)
	ListFeed(context.Context, *ListFeedRequest) (*ListFeedResponse, error)
	LikeTrip(context.Context, *LikeTripRequest) (*LikeTripResponse, error)
	DislikeTrip(context.Context, *DislikeTripRequest) (*DislikeTripResponse, error)
	AddToFavourites(context.Context, *AddToFavouritesRequest) (*AddToFavouritesResponse, error)
	RemoveFromFavourites(context.Context, *RemoveFromFavouritesRequest) (*RemoveFromFavouritesResponse, error)
	ListFavourites(context.Context, *ListFavouritesRequest) (*ListFavouritesResponse, error)
	// PINZ-131: Добавление медиа в существующий трип (ТЗ 5.1-5.3)
	AddMediaStart(context.Context, *AddMediaStartRequest) (*AddMediaStartResponse, error)
	AddMediaProcessGrouping(context.Context, *AddMediaProcessGroupingRequest) (*AddMediaProcessGroupingResponse, error)
	AddMediaApplyGroupsAndProcess(context.Context, *AddMediaApplyGroupsAndProcessRequest) (*AddMediaApplyGroupsAndProcessResponse, error)
	mustEmbedUnimplementedTripServiceServer()
}

// UnimplementedTripServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTripServiceServer struct{}

func (UnimplementedTripServiceServer) CreateTrip(context.Context, *CreateTripRequest) (*CreateTripResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTrip not implemented")
}
func (UnimplementedTripServiceServer) GetTrip(context.Context, *GetTripRequest) (*GetTripResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTrip not implemented")
}
func (UnimplementedTripServiceServer) ListUserTrips(context.Context, *ListUserTripsRequest) (*ListUserTripsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUserTrips not implemented")
}
func (UnimplementedTripServiceServer) UpdateTrip(context.Context, *UpdateTripRequest) (*UpdateTripResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTrip not implemented")
}
func (UnimplementedTripServiceServer) DeleteTrip(context.Context, *DeleteTripRequest) (*DeleteTripResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTrip not implemented")
}
func (UnimplementedTripServiceServer) RequestTripCoverUpload(context.Context, *RequestTripCoverUploadRequest) (*RequestTripCoverUploadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestTripCoverUpload not implemented")
}
func (UnimplementedTripServiceServer) ConfirmTripCoverUpload(context.Context, *ConfirmTripCoverUploadRequest) (*ConfirmTripCoverUploadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmTripCoverUpload not implemented")
}
func (UnimplementedTripServiceServer) DeleteTripCover(context.Context, *DeleteTripCoverRequest) (*DeleteTripCoverResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTripCover not implemented")
}
func (UnimplementedTripServiceServer) GenerateInviteLink(context.Context, *GenerateInviteLinkRequest) (*GenerateInviteLinkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateInviteLink not implemented")
}
func (UnimplementedTripServiceServer) JoinTripByToken(context.Context, *JoinTripByTokenRequest) (*JoinTripByTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinTripByToken not implemented")
}
func (UnimplementedTripServiceServer) RemoveParticipant(context.Context, *RemoveParticipantRequest) (*RemoveParticipantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveParticipant not implemented")
}
func (UnimplementedTripServiceServer) LeaveTrip(context.Context, *LeaveTripRequest) (*LeaveTripResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LeaveTrip not implemented")
}
func (UnimplementedTripServiceServer) TransferAdmin(context.Context, *TransferAdminRequest) (*TransferAdminResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransferAdmin not implemented")
}
func (UnimplementedTripServiceServer) ProcessMediaGrouping(context.Context, *ProcessMediaGroupingRequest) (*ProcessMediaGroupingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessMediaGrouping not implemented")
}
func (UnimplementedTripServiceServer) ApplyGroupsAndProcess(context.Context, *ApplyGroupsAndProcessRequest) (*ApplyGroupsAndProcessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyGroupsAndProcess not implemented")
}
func (UnimplementedTripServiceServer) GetTripReview(context.Context, *GetTripReviewRequest) (*GetTripReviewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTripReview not implemented")
}
func (UnimplementedTripServiceServer) FinalizeTrip(context.Context, *FinalizeTripRequest) (*FinalizeTripResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FinalizeTrip not implemented")
}
func (UnimplementedTripServiceServer) PublishTrip(context.Context, *PublishTripRequest) (*PublishTripResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishTrip not implemented")
}
func (UnimplementedTripServiceServer) UpdateTripSettings(context.Context, *UpdateTripSettingsRequest) (*UpdateTripSettingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTripSettings not implemented")
}
func (UnimplementedTripServiceServer) ListFeed(context.Context, *ListFeedRequest) (*ListFeedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFeed not implemented")
}
func (UnimplementedTripServiceServer) LikeTrip(context.Context, *LikeTripRequest) (*LikeTripResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LikeTrip not implemented")
}
func (UnimplementedTripServiceServer) DislikeTrip(context.Context, *DislikeTripRequest) (*DislikeTripResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DislikeTrip not implemented")
}
func (UnimplementedTripServiceServer) AddToFavourites(context.Context, *AddToFavouritesRequest) (*AddToFavouritesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddToFavourites not implemented")
}
func (UnimplementedTripServiceServer) RemoveFromFavourites(context.Context, *RemoveFromFavouritesRequest) (*RemoveFromFavouritesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveFromFavourites not implemented")
}
func (UnimplementedTripServiceServer) ListFavourites(context.Context, *ListFavouritesRequest) (*ListFavouritesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFavourites not implemented")
}
func (UnimplementedTripServiceServer) AddMediaStart(context.Context, *AddMediaStartRequest) (*AddMediaStartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddMediaStart not implemented")
}
func (UnimplementedTripServiceServer) AddMediaProcessGrouping(context.Context, *AddMediaProcessGroupingRequest) (*AddMediaProcessGroupingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddMediaProcessGrouping not implemented")
}
func (UnimplementedTripServiceServer) AddMediaApplyGroupsAndProcess(context.Context, *AddMediaApplyGroupsAndProcessRequest) (*AddMediaApplyGroupsAndProcessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddMediaApplyGroupsAndProcess not implemented")
}
func (UnimplementedTripServiceServer) mustEmbedUnimplementedTripServiceServer() {}
func (UnimplementedTripServiceServer) testEmbeddedByValue()                     {}

// UnsafeTripServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TripServiceServer will
// result in compilation errors.
type UnsafeTripServiceServer interface {
	mustEmbedUnimplementedTripServiceServer()
}

func RegisterTripServiceServer(s grpc.ServiceRegistrar, srv TripServiceServer) {
	// If the following call pancis, it indicates UnimplementedTripServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TripService_ServiceDesc, srv)
}

func _TripService_CreateTrip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTripRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).CreateTrip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_CreateTrip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).CreateTrip(ctx, req.(*CreateTripRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_GetTrip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTripRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).GetTrip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_GetTrip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).GetTrip(ctx, req.(*GetTripRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_ListUserTrips_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserTripsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).ListUserTrips(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_ListUserTrips_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).ListUserTrips(ctx, req.(*ListUserTripsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_UpdateTrip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTripRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).UpdateTrip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_UpdateTrip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).UpdateTrip(ctx, req.(*UpdateTripRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_DeleteTrip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTripRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).DeleteTrip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_DeleteTrip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).DeleteTrip(ctx, req.(*DeleteTripRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_RequestTripCoverUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestTripCoverUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).RequestTripCoverUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_RequestTripCoverUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).RequestTripCoverUpload(ctx, req.(*RequestTripCoverUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_ConfirmTripCoverUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmTripCoverUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).ConfirmTripCoverUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_ConfirmTripCoverUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).ConfirmTripCoverUpload(ctx, req.(*ConfirmTripCoverUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_DeleteTripCover_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTripCoverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).DeleteTripCover(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_DeleteTripCover_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).DeleteTripCover(ctx, req.(*DeleteTripCoverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_GenerateInviteLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateInviteLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).GenerateInviteLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_GenerateInviteLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).GenerateInviteLink(ctx, req.(*GenerateInviteLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_JoinTripByToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinTripByTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).JoinTripByToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_JoinTripByToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).JoinTripByToken(ctx, req.(*JoinTripByTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_RemoveParticipant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveParticipantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).RemoveParticipant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_RemoveParticipant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).RemoveParticipant(ctx, req.(*RemoveParticipantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_LeaveTrip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaveTripRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).LeaveTrip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_LeaveTrip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).LeaveTrip(ctx, req.(*LeaveTripRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_TransferAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).TransferAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_TransferAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).TransferAdmin(ctx, req.(*TransferAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_ProcessMediaGrouping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessMediaGroupingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).ProcessMediaGrouping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_ProcessMediaGrouping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).ProcessMediaGrouping(ctx, req.(*ProcessMediaGroupingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_ApplyGroupsAndProcess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyGroupsAndProcessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).ApplyGroupsAndProcess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_ApplyGroupsAndProcess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).ApplyGroupsAndProcess(ctx, req.(*ApplyGroupsAndProcessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_GetTripReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTripReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).GetTripReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_GetTripReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).GetTripReview(ctx, req.(*GetTripReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_FinalizeTrip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinalizeTripRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).FinalizeTrip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_FinalizeTrip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).FinalizeTrip(ctx, req.(*FinalizeTripRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_PublishTrip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishTripRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).PublishTrip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_PublishTrip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).PublishTrip(ctx, req.(*PublishTripRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_UpdateTripSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTripSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).UpdateTripSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_UpdateTripSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).UpdateTripSettings(ctx, req.(*UpdateTripSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_ListFeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFeedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).ListFeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_ListFeed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).ListFeed(ctx, req.(*ListFeedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_LikeTrip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LikeTripRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).LikeTrip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_LikeTrip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).LikeTrip(ctx, req.(*LikeTripRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_DislikeTrip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DislikeTripRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).DislikeTrip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_DislikeTrip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).DislikeTrip(ctx, req.(*DislikeTripRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_AddToFavourites_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddToFavouritesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).AddToFavourites(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_AddToFavourites_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).AddToFavourites(ctx, req.(*AddToFavouritesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_RemoveFromFavourites_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveFromFavouritesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).RemoveFromFavourites(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_RemoveFromFavourites_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).RemoveFromFavourites(ctx, req.(*RemoveFromFavouritesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_ListFavourites_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFavouritesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).ListFavourites(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_ListFavourites_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).ListFavourites(ctx, req.(*ListFavouritesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_AddMediaStart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMediaStartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).AddMediaStart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_AddMediaStart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).AddMediaStart(ctx, req.(*AddMediaStartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_AddMediaProcessGrouping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMediaProcessGroupingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).AddMediaProcessGrouping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_AddMediaProcessGrouping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).AddMediaProcessGrouping(ctx, req.(*AddMediaProcessGroupingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_AddMediaApplyGroupsAndProcess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMediaApplyGroupsAndProcessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).AddMediaApplyGroupsAndProcess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_AddMediaApplyGroupsAndProcess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).AddMediaApplyGroupsAndProcess(ctx, req.(*AddMediaApplyGroupsAndProcessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TripService_ServiceDesc is the grpc.ServiceDesc for TripService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TripService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "trip.TripService",
	HandlerType: (*TripServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTrip",
			Handler:    _TripService_CreateTrip_Handler,
		},
		{
			MethodName: "GetTrip",
			Handler:    _TripService_GetTrip_Handler,
		},
		{
			MethodName: "ListUserTrips",
			Handler:    _TripService_ListUserTrips_Handler,
		},
		{
			MethodName: "UpdateTrip",
			Handler:    _TripService_UpdateTrip_Handler,
		},
		{
			MethodName: "DeleteTrip",
			Handler:    _TripService_DeleteTrip_Handler,
		},
		{
			MethodName: "RequestTripCoverUpload",
			Handler:    _TripService_RequestTripCoverUpload_Handler,
		},
		{
			MethodName: "ConfirmTripCoverUpload",
			Handler:    _TripService_ConfirmTripCoverUpload_Handler,
		},
		{
			MethodName: "DeleteTripCover",
			Handler:    _TripService_DeleteTripCover_Handler,
		},
		{
			MethodName: "GenerateInviteLink",
			Handler:    _TripService_GenerateInviteLink_Handler,
		},
		{
			MethodName: "JoinTripByToken",
			Handler:    _TripService_JoinTripByToken_Handler,
		},
		{
			MethodName: "RemoveParticipant",
			Handler:    _TripService_RemoveParticipant_Handler,
		},
		{
			MethodName: "LeaveTrip",
			Handler:    _TripService_LeaveTrip_Handler,
		},
		{
			MethodName: "TransferAdmin",
			Handler:    _TripService_TransferAdmin_Handler,
		},
		{
			MethodName: "ProcessMediaGrouping",
			Handler:    _TripService_ProcessMediaGrouping_Handler,
		},
		{
			MethodName: "ApplyGroupsAndProcess",
			Handler:    _TripService_ApplyGroupsAndProcess_Handler,
		},
		{
			MethodName: "GetTripReview",
			Handler:    _TripService_GetTripReview_Handler,
		},
		{
			MethodName: "FinalizeTrip",
			Handler:    _TripService_FinalizeTrip_Handler,
		},
		{
			MethodName: "PublishTrip",
			Handler:    _TripService_PublishTrip_Handler,
		},
		{
			MethodName: "UpdateTripSettings",
			Handler:    _TripService_UpdateTripSettings_Handler,
		},
		{
			MethodName: "ListFeed",
			Handler:    _TripService_ListFeed_Handler,
		},
		{
			MethodName: "LikeTrip",
			Handler:    _TripService_LikeTrip_Handler,
		},
		{
			MethodName: "DislikeTrip",
			Handler:    _TripService_DislikeTrip_Handler,
		},
		{
			MethodName: "AddToFavourites",
			Handler:    _TripService_AddToFavourites_Handler,
		},
		{
			MethodName: "RemoveFromFavourites",
			Handler:    _TripService_RemoveFromFavourites_Handler,
		},
		{
			MethodName: "ListFavourites",
			Handler:    _TripService_ListFavourites_Handler,
		},
		{
			MethodName: "AddMediaStart",
			Handler:    _TripService_AddMediaStart_Handler,
		},
		{
			MethodName: "AddMediaProcessGrouping",
			Handler:    _TripService_AddMediaProcessGrouping_Handler,
		},
		{
			MethodName: "AddMediaApplyGroupsAndProcess",
			Handler:    _TripService_AddMediaApplyGroupsAndProcess_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "trip.proto",
}
