// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: trip.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Trip struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerUserId   string                 `protobuf:"bytes,2,opt,name=owner_user_id,json=ownerUserId,proto3" json:"owner_user_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Category      string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	Season        string                 `protobuf:"bytes,6,opt,name=season,proto3" json:"season,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	PrivacyLevel  string                 `protobuf:"bytes,8,opt,name=privacy_level,json=privacyLevel,proto3" json:"privacy_level,omitempty"`
	StartDateUnix int64                  `protobuf:"varint,9,opt,name=start_date_unix,json=startDateUnix,proto3" json:"start_date_unix,omitempty"`
	EndDateUnix   int64                  `protobuf:"varint,10,opt,name=end_date_unix,json=endDateUnix,proto3" json:"end_date_unix,omitempty"`
	LikesCount    int32                  `protobuf:"varint,11,opt,name=likes_count,json=likesCount,proto3" json:"likes_count,omitempty"`
	DislikesCount int32                  `protobuf:"varint,12,opt,name=dislikes_count,json=dislikesCount,proto3" json:"dislikes_count,omitempty"`
	CoverUrl      string                 `protobuf:"bytes,13,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`
	IsPublished   bool                   `protobuf:"varint,14,opt,name=is_published,json=isPublished,proto3" json:"is_published,omitempty"`
	IsGenerated   bool                   `protobuf:"varint,15,opt,name=is_generated,json=isGenerated,proto3" json:"is_generated,omitempty"`
	CreatedAtUnix int64                  `protobuf:"varint,16,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
	UpdatedAtUnix int64                  `protobuf:"varint,17,opt,name=updated_at_unix,json=updatedAtUnix,proto3" json:"updated_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trip) Reset() {
	*x = Trip{}
	mi := &file_trip_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trip) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trip) ProtoMessage() {}

func (x *Trip) ProtoReflect() protoreflect.Message {
	mi := &file_trip_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trip.ProtoReflect.Descriptor instead.
func (*Trip) Descriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{0}
}

func (x *Trip) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Trip) GetOwnerUserId() string {
	if x != nil {
		return x.OwnerUserId
	}
	return ""
}

func (x *Trip) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Trip) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Trip) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Trip) GetSeason() string {
	if x != nil {
		return x.Season
	}
	return ""
}

func (x *Trip) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Trip) GetPrivacyLevel() string {
	if x != nil {
		return x.PrivacyLevel
	}
	return ""
}

func (x *Trip) GetStartDateUnix() int64 {
	if x != nil {
		return x.StartDateUnix
	}
	return 0
}

func (x *Trip) GetEndDateUnix() int64 {
	if x != nil {
		return x.EndDateUnix
	}
	return 0
}

func (x *Trip) GetLikesCount() int32 {
	if x != nil {
		return x.LikesCount
	}
	return 0
}

func (x *Trip) GetDislikesCount() int32 {
	if x != nil {
		return x.DislikesCount
	}
	return 0
}

func (x *Trip) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *Trip) GetIsPublished() bool {
	if x != nil {
		return x.IsPublished
	}
	return false
}

func (x *Trip) GetIsGenerated() bool {
	if x != nil {
		return x.IsGenerated
	}
	return false
}

func (x *Trip) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

func (x *Trip) GetUpdatedAtUnix() int64 {
	if x != nil {
		return x.UpdatedAtUnix
	}
	return 0
}

type CreateTripRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerUserId   string                 `protobuf:"bytes,1,opt,name=owner_user_id,json=ownerUserId,proto3" json:"owner_user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Season        string                 `protobuf:"bytes,5,opt,name=season,proto3" json:"season,omitempty"`
	PrivacyLevel  string                 `protobuf:"bytes,6,opt,name=privacy_level,json=privacyLevel,proto3" json:"privacy_level,omitempty"`
	FilesToUpload []*FileToUpload        `protobuf:"bytes,7,rep,name=files_to_upload,json=filesToUpload,proto3" json:"files_to_upload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTripRequest) Reset() {
	*x = CreateTripRequest{}
	mi := &file_trip_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTripRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTripRequest) ProtoMessage() {}

func (x *CreateTripRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trip_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTripRequest.ProtoReflect.Descriptor instead.
func (*CreateTripRequest) Descriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTripRequest) GetOwnerUserId() string {
	if x != nil {
		return x.OwnerUserId
	}
	return ""
}

func (x *CreateTripRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTripRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateTripRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CreateTripRequest) GetSeason() string {
	if x != nil {
		return x.Season
	}
	return ""
}

func (x *CreateTripRequest) GetPrivacyLevel() string {
	if x != nil {
		return x.PrivacyLevel
	}
	return ""
}

func (x *CreateTripRequest) GetFilesToUpload() []*FileToUpload {
	if x != nil {
		return x.FilesToUpload
	}
	return nil
}

type FileToUpload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileToUpload) Reset() {
	*x = FileToUpload{}
	mi := &file_trip_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileToUpload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileToUpload) ProtoMessage() {}

func (x *FileToUpload) ProtoReflect() protoreflect.Message {
	mi := &file_trip_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileToUpload.ProtoReflect.Descriptor instead.
func (*FileToUpload) Descriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{2}
}

func (x *FileToUpload) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *FileToUpload) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type CreateTripResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TripId        string                 `protobuf:"bytes,1,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	UploadUrls    []*UploadUrl           `protobuf:"bytes,3,rep,name=upload_urls,json=uploadUrls,proto3" json:"upload_urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTripResponse) Reset() {
	*x = CreateTripResponse{}
	mi := &file_trip_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTripResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTripResponse) ProtoMessage() {}

func (x *CreateTripResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trip_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTripResponse.ProtoReflect.Descriptor instead.
func (*CreateTripResponse) Descriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{3}
}

func (x *CreateTripResponse) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

func (x *CreateTripResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateTripResponse) GetUploadUrls() []*UploadUrl {
	if x != nil {
		return x.UploadUrls
	}
	return nil
}

type UploadUrl struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	S3Key         string                 `protobuf:"bytes,2,opt,name=s3_key,json=s3Key,proto3" json:"s3_key,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadUrl) Reset() {
	*x = UploadUrl{}
	mi := &file_trip_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadUrl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadUrl) ProtoMessage() {}

func (x *UploadUrl) ProtoReflect() protoreflect.Message {
	mi := &file_trip_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadUrl.ProtoReflect.Descriptor instead.
func (*UploadUrl) Descriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{4}
}

func (x *UploadUrl) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *UploadUrl) GetS3Key() string {
	if x != nil {
		return x.S3Key
	}
	return ""
}

func (x *UploadUrl) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type GetTripRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TripId        string                 `protobuf:"bytes,1,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTripRequest) Reset() {
	*x = GetTripRequest{}
	mi := &file_trip_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTripRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTripRequest) ProtoMessage() {}

func (x *GetTripRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trip_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTripRequest.ProtoReflect.Descriptor instead.
func (*GetTripRequest) Descriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{5}
}

func (x *GetTripRequest) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

func (x *GetTripRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetTripResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trip          *Trip                  `protobuf:"bytes,1,opt,name=trip,proto3" json:"trip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTripResponse) Reset() {
	*x = GetTripResponse{}
	mi := &file_trip_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTripResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTripResponse) ProtoMessage() {}

func (x *GetTripResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trip_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTripResponse.ProtoReflect.Descriptor instead.
func (*GetTripResponse) Descriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{6}
}

func (x *GetTripResponse) GetTrip() *Trip {
	if x != nil {
		return x.Trip
	}
	return nil
}

type ListUserTripsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserTripsRequest) Reset() {
	*x = ListUserTripsRequest{}
	mi := &file_trip_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserTripsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserTripsRequest) ProtoMessage() {}

func (x *ListUserTripsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trip_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserTripsRequest.ProtoReflect.Descriptor instead.
func (*ListUserTripsRequest) Descriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{7}
}

func (x *ListUserTripsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListUserTripsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListUserTripsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListUserTripsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trips         []*Trip                `protobuf:"bytes,1,rep,name=trips,proto3" json:"trips,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserTripsResponse) Reset() {
	*x = ListUserTripsResponse{}
	mi := &file_trip_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserTripsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserTripsResponse) ProtoMessage() {}

func (x *ListUserTripsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trip_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserTripsResponse.ProtoReflect.Descriptor instead.
func (*ListUserTripsResponse) Descriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{8}
}

func (x *ListUserTripsResponse) GetTrips() []*Trip {
	if x != nil {
		return x.Trips
	}
	return nil
}

type UpdateTripRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TripId        string                 `protobuf:"bytes,1,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          *string                `protobuf:"bytes,3,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Category      *string                `protobuf:"bytes,5,opt,name=category,proto3,oneof" json:"category,omitempty"`
	Season        *string                `protobuf:"bytes,6,opt,name=season,proto3,oneof" json:"season,omitempty"`
	PrivacyLevel  *string                `protobuf:"bytes,7,opt,name=privacy_level,json=privacyLevel,proto3,oneof" json:"privacy_level,omitempty"`
	StartDateUnix *int64                 `protobuf:"varint,8,opt,name=start_date_unix,json=startDateUnix,proto3,oneof" json:"start_date_unix,omitempty"`
	EndDateUnix   *int64                 `protobuf:"varint,9,opt,name=end_date_unix,json=endDateUnix,proto3,oneof" json:"end_date_unix,omitempty"`
	CoverUrl      *string                `protobuf:"bytes,10,opt,name=cover_url,json=coverUrl,proto3,oneof" json:"cover_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTripRequest) Reset() {
	*x = UpdateTripRequest{}
	mi := &file_trip_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTripRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTripRequest) ProtoMessage() {}

func (x *UpdateTripRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trip_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTripRequest.ProtoReflect.Descriptor instead.
func (*UpdateTripRequest) Descriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateTripRequest) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

func (x *UpdateTripRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateTripRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateTripRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateTripRequest) GetCategory() string {
	if x != nil && x.Category != nil {
		return *x.Category
	}
	return ""
}

func (x *UpdateTripRequest) GetSeason() string {
	if x != nil && x.Season != nil {
		return *x.Season
	}
	return ""
}

func (x *UpdateTripRequest) GetPrivacyLevel() string {
	if x != nil && x.PrivacyLevel != nil {
		return *x.PrivacyLevel
	}
	return ""
}

func (x *UpdateTripRequest) GetStartDateUnix() int64 {
	if x != nil && x.StartDateUnix != nil {
		return *x.StartDateUnix
	}
	return 0
}

func (x *UpdateTripRequest) GetEndDateUnix() int64 {
	if x != nil && x.EndDateUnix != nil {
		return *x.EndDateUnix
	}
	return 0
}

func (x *UpdateTripRequest) GetCoverUrl() string {
	if x != nil && x.CoverUrl != nil {
		return *x.CoverUrl
	}
	return ""
}

type UpdateTripResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trip          *Trip                  `protobuf:"bytes,1,opt,name=trip,proto3" json:"trip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTripResponse) Reset() {
	*x = UpdateTripResponse{}
	mi := &file_trip_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTripResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTripResponse) ProtoMessage() {}

func (x *UpdateTripResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trip_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTripResponse.ProtoReflect.Descriptor instead.
func (*UpdateTripResponse) Descriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateTripResponse) GetTrip() *Trip {
	if x != nil {
		return x.Trip
	}
	return nil
}

type DeleteTripRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TripId        string                 `protobuf:"bytes,1,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTripRequest) Reset() {
	*x = DeleteTripRequest{}
	mi := &file_trip_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTripRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTripRequest) ProtoMessage() {}

func (x *DeleteTripRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trip_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTripRequest.ProtoReflect.Descriptor instead.
func (*DeleteTripRequest) Descriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteTripRequest) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

func (x *DeleteTripRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteTripResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTripResponse) Reset() {
	*x = DeleteTripResponse{}
	mi := &file_trip_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTripResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTripResponse) ProtoMessage() {}

func (x *DeleteTripResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trip_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTripResponse.ProtoReflect.Descriptor instead.
func (*DeleteTripResponse) Descriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteTripResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ProcessMediaGroupingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessMediaGroupingRequest) Reset() {
	*x = ProcessMediaGroupingRequest{}
	mi := &file_trip_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessMediaGroupingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessMediaGroupingRequest) ProtoMessage() {}

func (x *ProcessMediaGroupingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trip_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessMediaGroupingRequest.ProtoReflect.Descriptor instead.
func (*ProcessMediaGroupingRequest) Descriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{13}
}

type ProcessMediaGroupingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessMediaGroupingResponse) Reset() {
	*x = ProcessMediaGroupingResponse{}
	mi := &file_trip_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessMediaGroupingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessMediaGroupingResponse) ProtoMessage() {}

func (x *ProcessMediaGroupingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trip_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessMediaGroupingResponse.ProtoReflect.Descriptor instead.
func (*ProcessMediaGroupingResponse) Descriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{14}
}

type ApplyGroupsAndProcessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyGroupsAndProcessRequest) Reset() {
	*x = ApplyGroupsAndProcessRequest{}
	mi := &file_trip_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyGroupsAndProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyGroupsAndProcessRequest) ProtoMessage() {}

func (x *ApplyGroupsAndProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trip_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyGroupsAndProcessRequest.ProtoReflect.Descriptor instead.
func (*ApplyGroupsAndProcessRequest) Descriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{15}
}

type ApplyGroupsAndProcessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyGroupsAndProcessResponse) Reset() {
	*x = ApplyGroupsAndProcessResponse{}
	mi := &file_trip_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyGroupsAndProcessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyGroupsAndProcessResponse) ProtoMessage() {}

func (x *ApplyGroupsAndProcessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trip_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyGroupsAndProcessResponse.ProtoReflect.Descriptor instead.
func (*ApplyGroupsAndProcessResponse) Descriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{16}
}

type GetTripReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTripReviewRequest) Reset() {
	*x = GetTripReviewRequest{}
	mi := &file_trip_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTripReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTripReviewRequest) ProtoMessage() {}

func (x *GetTripReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trip_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTripReviewRequest.ProtoReflect.Descriptor instead.
func (*GetTripReviewRequest) Descriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{17}
}

type GetTripReviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTripReviewResponse) Reset() {
	*x = GetTripReviewResponse{}
	mi := &file_trip_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTripReviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTripReviewResponse) ProtoMessage() {}

func (x *GetTripReviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trip_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTripReviewResponse.ProtoReflect.Descriptor instead.
func (*GetTripReviewResponse) Descriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{18}
}

type FinalizeTripRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalizeTripRequest) Reset() {
	*x = FinalizeTripRequest{}
	mi := &file_trip_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizeTripRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeTripRequest) ProtoMessage() {}

func (x *FinalizeTripRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trip_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeTripRequest.ProtoReflect.Descriptor instead.
func (*FinalizeTripRequest) Descriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{19}
}

type FinalizeTripResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalizeTripResponse) Reset() {
	*x = FinalizeTripResponse{}
	mi := &file_trip_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizeTripResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeTripResponse) ProtoMessage() {}

func (x *FinalizeTripResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trip_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeTripResponse.ProtoReflect.Descriptor instead.
func (*FinalizeTripResponse) Descriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{20}
}

// Участники и инвайты
type GenerateInviteLinkRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TripId           string                 `protobuf:"bytes,1,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	ExpiresInSeconds int64                  `protobuf:"varint,2,opt,name=expires_in_seconds,json=expiresInSeconds,proto3" json:"expires_in_seconds,omitempty"` // TTL ссылки, например 86400 = 24 часа
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GenerateInviteLinkRequest) Reset() {
	*x = GenerateInviteLinkRequest{}
	mi := &file_trip_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateInviteLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateInviteLinkRequest) ProtoMessage() {}

func (x *GenerateInviteLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trip_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateInviteLinkRequest.ProtoReflect.Descriptor instead.
func (*GenerateInviteLinkRequest) Descriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{21}
}

func (x *GenerateInviteLinkRequest) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

func (x *GenerateInviteLinkRequest) GetExpiresInSeconds() int64 {
	if x != nil {
		return x.ExpiresInSeconds
	}
	return 0
}

type GenerateInviteLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InviteLinkId  string                 `protobuf:"bytes,1,opt,name=invite_link_id,json=inviteLinkId,proto3" json:"invite_link_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	InviteUrl     string                 `protobuf:"bytes,3,opt,name=invite_url,json=inviteUrl,proto3" json:"invite_url,omitempty"` // полный URL для шаринга (клиент или gateway может собрать)
	ExpiresAtUnix int64                  `protobuf:"varint,4,opt,name=expires_at_unix,json=expiresAtUnix,proto3" json:"expires_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateInviteLinkResponse) Reset() {
	*x = GenerateInviteLinkResponse{}
	mi := &file_trip_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateInviteLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateInviteLinkResponse) ProtoMessage() {}

func (x *GenerateInviteLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trip_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateInviteLinkResponse.ProtoReflect.Descriptor instead.
func (*GenerateInviteLinkResponse) Descriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{22}
}

func (x *GenerateInviteLinkResponse) GetInviteLinkId() string {
	if x != nil {
		return x.InviteLinkId
	}
	return ""
}

func (x *GenerateInviteLinkResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GenerateInviteLinkResponse) GetInviteUrl() string {
	if x != nil {
		return x.InviteUrl
	}
	return ""
}

func (x *GenerateInviteLinkResponse) GetExpiresAtUnix() int64 {
	if x != nil {
		return x.ExpiresAtUnix
	}
	return 0
}

type JoinTripByTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinTripByTokenRequest) Reset() {
	*x = JoinTripByTokenRequest{}
	mi := &file_trip_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinTripByTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinTripByTokenRequest) ProtoMessage() {}

func (x *JoinTripByTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trip_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinTripByTokenRequest.ProtoReflect.Descriptor instead.
func (*JoinTripByTokenRequest) Descriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{23}
}

func (x *JoinTripByTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type JoinTripByTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TripId        string                 `protobuf:"bytes,1,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	AlreadyJoined bool                   `protobuf:"varint,2,opt,name=already_joined,json=alreadyJoined,proto3" json:"already_joined,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinTripByTokenResponse) Reset() {
	*x = JoinTripByTokenResponse{}
	mi := &file_trip_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinTripByTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinTripByTokenResponse) ProtoMessage() {}

func (x *JoinTripByTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trip_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinTripByTokenResponse.ProtoReflect.Descriptor instead.
func (*JoinTripByTokenResponse) Descriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{24}
}

func (x *JoinTripByTokenResponse) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

func (x *JoinTripByTokenResponse) GetAlreadyJoined() bool {
	if x != nil {
		return x.AlreadyJoined
	}
	return false
}

type RemoveParticipantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TripId        string                 `protobuf:"bytes,1,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // участник, которого удаляем
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveParticipantRequest) Reset() {
	*x = RemoveParticipantRequest{}
	mi := &file_trip_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveParticipantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveParticipantRequest) ProtoMessage() {}

func (x *RemoveParticipantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trip_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveParticipantRequest.ProtoReflect.Descriptor instead.
func (*RemoveParticipantRequest) Descriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{25}
}

func (x *RemoveParticipantRequest) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

func (x *RemoveParticipantRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type RemoveParticipantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveParticipantResponse) Reset() {
	*x = RemoveParticipantResponse{}
	mi := &file_trip_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveParticipantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveParticipantResponse) ProtoMessage() {}

func (x *RemoveParticipantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trip_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveParticipantResponse.ProtoReflect.Descriptor instead.
func (*RemoveParticipantResponse) Descriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{26}
}

func (x *RemoveParticipantResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type LeaveTripRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TripId        string                 `protobuf:"bytes,1,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveTripRequest) Reset() {
	*x = LeaveTripRequest{}
	mi := &file_trip_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveTripRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveTripRequest) ProtoMessage() {}

func (x *LeaveTripRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trip_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveTripRequest.ProtoReflect.Descriptor instead.
func (*LeaveTripRequest) Descriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{27}
}

func (x *LeaveTripRequest) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

type LeaveTripResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	TripDeleted   bool                   `protobuf:"varint,2,opt,name=trip_deleted,json=tripDeleted,proto3" json:"trip_deleted,omitempty"` // true если трип удалён (был единственный участник)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveTripResponse) Reset() {
	*x = LeaveTripResponse{}
	mi := &file_trip_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveTripResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveTripResponse) ProtoMessage() {}

func (x *LeaveTripResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trip_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveTripResponse.ProtoReflect.Descriptor instead.
func (*LeaveTripResponse) Descriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{28}
}

func (x *LeaveTripResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LeaveTripResponse) GetTripDeleted() bool {
	if x != nil {
		return x.TripDeleted
	}
	return false
}

type TransferAdminRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TripId         string                 `protobuf:"bytes,1,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	NewAdminUserId string                 `protobuf:"bytes,2,opt,name=new_admin_user_id,json=newAdminUserId,proto3" json:"new_admin_user_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TransferAdminRequest) Reset() {
	*x = TransferAdminRequest{}
	mi := &file_trip_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferAdminRequest) ProtoMessage() {}

func (x *TransferAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trip_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferAdminRequest.ProtoReflect.Descriptor instead.
func (*TransferAdminRequest) Descriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{29}
}

func (x *TransferAdminRequest) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

func (x *TransferAdminRequest) GetNewAdminUserId() string {
	if x != nil {
		return x.NewAdminUserId
	}
	return ""
}

type TransferAdminResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferAdminResponse) Reset() {
	*x = TransferAdminResponse{}
	mi := &file_trip_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferAdminResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferAdminResponse) ProtoMessage() {}

func (x *TransferAdminResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trip_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferAdminResponse.ProtoReflect.Descriptor instead.
func (*TransferAdminResponse) Descriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{30}
}

func (x *TransferAdminResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_trip_proto protoreflect.FileDescriptor

const file_trip_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"trip.proto\x12\x04trip\"\xa8\x04\n" +
	"\x04Trip\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\"\n" +
	"\rowner_user_id\x18\x02 \x01(\tR\vownerUserId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\x12\x16\n" +
	"\x06season\x18\x06 \x01(\tR\x06season\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12#\n" +
	"\rprivacy_level\x18\b \x01(\tR\fprivacyLevel\x12&\n" +
	"\x0fstart_date_unix\x18\t \x01(\x03R\rstartDateUnix\x12\"\n" +
	"\rend_date_unix\x18\n" +
	" \x01(\x03R\vendDateUnix\x12\x1f\n" +
	"\vlikes_count\x18\v \x01(\x05R\n" +
	"likesCount\x12%\n" +
	"\x0edislikes_count\x18\f \x01(\x05R\rdislikesCount\x12\x1b\n" +
	"\tcover_url\x18\r \x01(\tR\bcoverUrl\x12!\n" +
	"\fis_published\x18\x0e \x01(\bR\visPublished\x12!\n" +
	"\fis_generated\x18\x0f \x01(\bR\visGenerated\x12&\n" +
	"\x0fcreated_at_unix\x18\x10 \x01(\x03R\rcreatedAtUnix\x12&\n" +
	"\x0fupdated_at_unix\x18\x11 \x01(\x03R\rupdatedAtUnix\"\x82\x02\n" +
	"\x11CreateTripRequest\x12\"\n" +
	"\rowner_user_id\x18\x01 \x01(\tR\vownerUserId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12\x16\n" +
	"\x06season\x18\x05 \x01(\tR\x06season\x12#\n" +
	"\rprivacy_level\x18\x06 \x01(\tR\fprivacyLevel\x12:\n" +
	"\x0ffiles_to_upload\x18\a \x03(\v2\x12.trip.FileToUploadR\rfilesToUpload\"N\n" +
	"\fFileToUpload\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\"w\n" +
	"\x12CreateTripResponse\x12\x17\n" +
	"\atrip_id\x18\x01 \x01(\tR\x06tripId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x120\n" +
	"\vupload_urls\x18\x03 \x03(\v2\x0f.trip.UploadUrlR\n" +
	"uploadUrls\"Q\n" +
	"\tUploadUrl\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x15\n" +
	"\x06s3_key\x18\x02 \x01(\tR\x05s3Key\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\"B\n" +
	"\x0eGetTripRequest\x12\x17\n" +
	"\atrip_id\x18\x01 \x01(\tR\x06tripId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"1\n" +
	"\x0fGetTripResponse\x12\x1e\n" +
	"\x04trip\x18\x01 \x01(\v2\n" +
	".trip.TripR\x04trip\"]\n" +
	"\x14ListUserTripsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"9\n" +
	"\x15ListUserTripsResponse\x12 \n" +
	"\x05trips\x18\x01 \x03(\v2\n" +
	".trip.TripR\x05trips\"\xdc\x03\n" +
	"\x11UpdateTripRequest\x12\x17\n" +
	"\atrip_id\x18\x01 \x01(\tR\x06tripId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x17\n" +
	"\x04name\x18\x03 \x01(\tH\x00R\x04name\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x01R\vdescription\x88\x01\x01\x12\x1f\n" +
	"\bcategory\x18\x05 \x01(\tH\x02R\bcategory\x88\x01\x01\x12\x1b\n" +
	"\x06season\x18\x06 \x01(\tH\x03R\x06season\x88\x01\x01\x12(\n" +
	"\rprivacy_level\x18\a \x01(\tH\x04R\fprivacyLevel\x88\x01\x01\x12+\n" +
	"\x0fstart_date_unix\x18\b \x01(\x03H\x05R\rstartDateUnix\x88\x01\x01\x12'\n" +
	"\rend_date_unix\x18\t \x01(\x03H\x06R\vendDateUnix\x88\x01\x01\x12 \n" +
	"\tcover_url\x18\n" +
	" \x01(\tH\aR\bcoverUrl\x88\x01\x01B\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_descriptionB\v\n" +
	"\t_categoryB\t\n" +
	"\a_seasonB\x10\n" +
	"\x0e_privacy_levelB\x12\n" +
	"\x10_start_date_unixB\x10\n" +
	"\x0e_end_date_unixB\f\n" +
	"\n" +
	"_cover_url\"4\n" +
	"\x12UpdateTripResponse\x12\x1e\n" +
	"\x04trip\x18\x01 \x01(\v2\n" +
	".trip.TripR\x04trip\"E\n" +
	"\x11DeleteTripRequest\x12\x17\n" +
	"\atrip_id\x18\x01 \x01(\tR\x06tripId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\".\n" +
	"\x12DeleteTripResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x1d\n" +
	"\x1bProcessMediaGroupingRequest\"\x1e\n" +
	"\x1cProcessMediaGroupingResponse\"\x1e\n" +
	"\x1cApplyGroupsAndProcessRequest\"\x1f\n" +
	"\x1dApplyGroupsAndProcessResponse\"\x16\n" +
	"\x14GetTripReviewRequest\"\x17\n" +
	"\x15GetTripReviewResponse\"\x15\n" +
	"\x13FinalizeTripRequest\"\x16\n" +
	"\x14FinalizeTripResponse\"b\n" +
	"\x19GenerateInviteLinkRequest\x12\x17\n" +
	"\atrip_id\x18\x01 \x01(\tR\x06tripId\x12,\n" +
	"\x12expires_in_seconds\x18\x02 \x01(\x03R\x10expiresInSeconds\"\x9f\x01\n" +
	"\x1aGenerateInviteLinkResponse\x12$\n" +
	"\x0einvite_link_id\x18\x01 \x01(\tR\finviteLinkId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x1d\n" +
	"\n" +
	"invite_url\x18\x03 \x01(\tR\tinviteUrl\x12&\n" +
	"\x0fexpires_at_unix\x18\x04 \x01(\x03R\rexpiresAtUnix\".\n" +
	"\x16JoinTripByTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"Y\n" +
	"\x17JoinTripByTokenResponse\x12\x17\n" +
	"\atrip_id\x18\x01 \x01(\tR\x06tripId\x12%\n" +
	"\x0ealready_joined\x18\x02 \x01(\bR\ralreadyJoined\"L\n" +
	"\x18RemoveParticipantRequest\x12\x17\n" +
	"\atrip_id\x18\x01 \x01(\tR\x06tripId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"5\n" +
	"\x19RemoveParticipantResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"+\n" +
	"\x10LeaveTripRequest\x12\x17\n" +
	"\atrip_id\x18\x01 \x01(\tR\x06tripId\"P\n" +
	"\x11LeaveTripResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12!\n" +
	"\ftrip_deleted\x18\x02 \x01(\bR\vtripDeleted\"Z\n" +
	"\x14TransferAdminRequest\x12\x17\n" +
	"\atrip_id\x18\x01 \x01(\tR\x06tripId\x12)\n" +
	"\x11new_admin_user_id\x18\x02 \x01(\tR\x0enewAdminUserId\"1\n" +
	"\x15TransferAdminResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xab\b\n" +
	"\vTripService\x12?\n" +
	"\n" +
	"CreateTrip\x12\x17.trip.CreateTripRequest\x1a\x18.trip.CreateTripResponse\x126\n" +
	"\aGetTrip\x12\x14.trip.GetTripRequest\x1a\x15.trip.GetTripResponse\x12H\n" +
	"\rListUserTrips\x12\x1a.trip.ListUserTripsRequest\x1a\x1b.trip.ListUserTripsResponse\x12?\n" +
	"\n" +
	"UpdateTrip\x12\x17.trip.UpdateTripRequest\x1a\x18.trip.UpdateTripResponse\x12?\n" +
	"\n" +
	"DeleteTrip\x12\x17.trip.DeleteTripRequest\x1a\x18.trip.DeleteTripResponse\x12W\n" +
	"\x12GenerateInviteLink\x12\x1f.trip.GenerateInviteLinkRequest\x1a .trip.GenerateInviteLinkResponse\x12N\n" +
	"\x0fJoinTripByToken\x12\x1c.trip.JoinTripByTokenRequest\x1a\x1d.trip.JoinTripByTokenResponse\x12T\n" +
	"\x11RemoveParticipant\x12\x1e.trip.RemoveParticipantRequest\x1a\x1f.trip.RemoveParticipantResponse\x12<\n" +
	"\tLeaveTrip\x12\x16.trip.LeaveTripRequest\x1a\x17.trip.LeaveTripResponse\x12H\n" +
	"\rTransferAdmin\x12\x1a.trip.TransferAdminRequest\x1a\x1b.trip.TransferAdminResponse\x12]\n" +
	"\x14ProcessMediaGrouping\x12!.trip.ProcessMediaGroupingRequest\x1a\".trip.ProcessMediaGroupingResponse\x12`\n" +
	"\x15ApplyGroupsAndProcess\x12\".trip.ApplyGroupsAndProcessRequest\x1a#.trip.ApplyGroupsAndProcessResponse\x12H\n" +
	"\rGetTripReview\x12\x1a.trip.GetTripReviewRequest\x1a\x1b.trip.GetTripReviewResponse\x12E\n" +
	"\fFinalizeTrip\x12\x19.trip.FinalizeTripRequest\x1a\x1a.trip.FinalizeTripResponseB%Z#pinz/backend/trip-service/pkg/protob\x06proto3"

var (
	file_trip_proto_rawDescOnce sync.Once
	file_trip_proto_rawDescData []byte
)

func file_trip_proto_rawDescGZIP() []byte {
	file_trip_proto_rawDescOnce.Do(func() {
		file_trip_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_trip_proto_rawDesc), len(file_trip_proto_rawDesc)))
	})
	return file_trip_proto_rawDescData
}

var file_trip_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_trip_proto_goTypes = []any{
	(*Trip)(nil),                          // 0: trip.Trip
	(*CreateTripRequest)(nil),             // 1: trip.CreateTripRequest
	(*FileToUpload)(nil),                  // 2: trip.FileToUpload
	(*CreateTripResponse)(nil),            // 3: trip.CreateTripResponse
	(*UploadUrl)(nil),                     // 4: trip.UploadUrl
	(*GetTripRequest)(nil),                // 5: trip.GetTripRequest
	(*GetTripResponse)(nil),               // 6: trip.GetTripResponse
	(*ListUserTripsRequest)(nil),          // 7: trip.ListUserTripsRequest
	(*ListUserTripsResponse)(nil),         // 8: trip.ListUserTripsResponse
	(*UpdateTripRequest)(nil),             // 9: trip.UpdateTripRequest
	(*UpdateTripResponse)(nil),            // 10: trip.UpdateTripResponse
	(*DeleteTripRequest)(nil),             // 11: trip.DeleteTripRequest
	(*DeleteTripResponse)(nil),            // 12: trip.DeleteTripResponse
	(*ProcessMediaGroupingRequest)(nil),   // 13: trip.ProcessMediaGroupingRequest
	(*ProcessMediaGroupingResponse)(nil),  // 14: trip.ProcessMediaGroupingResponse
	(*ApplyGroupsAndProcessRequest)(nil),  // 15: trip.ApplyGroupsAndProcessRequest
	(*ApplyGroupsAndProcessResponse)(nil), // 16: trip.ApplyGroupsAndProcessResponse
	(*GetTripReviewRequest)(nil),          // 17: trip.GetTripReviewRequest
	(*GetTripReviewResponse)(nil),         // 18: trip.GetTripReviewResponse
	(*FinalizeTripRequest)(nil),           // 19: trip.FinalizeTripRequest
	(*FinalizeTripResponse)(nil),          // 20: trip.FinalizeTripResponse
	(*GenerateInviteLinkRequest)(nil),     // 21: trip.GenerateInviteLinkRequest
	(*GenerateInviteLinkResponse)(nil),    // 22: trip.GenerateInviteLinkResponse
	(*JoinTripByTokenRequest)(nil),        // 23: trip.JoinTripByTokenRequest
	(*JoinTripByTokenResponse)(nil),       // 24: trip.JoinTripByTokenResponse
	(*RemoveParticipantRequest)(nil),      // 25: trip.RemoveParticipantRequest
	(*RemoveParticipantResponse)(nil),     // 26: trip.RemoveParticipantResponse
	(*LeaveTripRequest)(nil),              // 27: trip.LeaveTripRequest
	(*LeaveTripResponse)(nil),             // 28: trip.LeaveTripResponse
	(*TransferAdminRequest)(nil),          // 29: trip.TransferAdminRequest
	(*TransferAdminResponse)(nil),         // 30: trip.TransferAdminResponse
}
var file_trip_proto_depIdxs = []int32{
	2,  // 0: trip.CreateTripRequest.files_to_upload:type_name -> trip.FileToUpload
	4,  // 1: trip.CreateTripResponse.upload_urls:type_name -> trip.UploadUrl
	0,  // 2: trip.GetTripResponse.trip:type_name -> trip.Trip
	0,  // 3: trip.ListUserTripsResponse.trips:type_name -> trip.Trip
	0,  // 4: trip.UpdateTripResponse.trip:type_name -> trip.Trip
	1,  // 5: trip.TripService.CreateTrip:input_type -> trip.CreateTripRequest
	5,  // 6: trip.TripService.GetTrip:input_type -> trip.GetTripRequest
	7,  // 7: trip.TripService.ListUserTrips:input_type -> trip.ListUserTripsRequest
	9,  // 8: trip.TripService.UpdateTrip:input_type -> trip.UpdateTripRequest
	11, // 9: trip.TripService.DeleteTrip:input_type -> trip.DeleteTripRequest
	21, // 10: trip.TripService.GenerateInviteLink:input_type -> trip.GenerateInviteLinkRequest
	23, // 11: trip.TripService.JoinTripByToken:input_type -> trip.JoinTripByTokenRequest
	25, // 12: trip.TripService.RemoveParticipant:input_type -> trip.RemoveParticipantRequest
	27, // 13: trip.TripService.LeaveTrip:input_type -> trip.LeaveTripRequest
	29, // 14: trip.TripService.TransferAdmin:input_type -> trip.TransferAdminRequest
	13, // 15: trip.TripService.ProcessMediaGrouping:input_type -> trip.ProcessMediaGroupingRequest
	15, // 16: trip.TripService.ApplyGroupsAndProcess:input_type -> trip.ApplyGroupsAndProcessRequest
	17, // 17: trip.TripService.GetTripReview:input_type -> trip.GetTripReviewRequest
	19, // 18: trip.TripService.FinalizeTrip:input_type -> trip.FinalizeTripRequest
	3,  // 19: trip.TripService.CreateTrip:output_type -> trip.CreateTripResponse
	6,  // 20: trip.TripService.GetTrip:output_type -> trip.GetTripResponse
	8,  // 21: trip.TripService.ListUserTrips:output_type -> trip.ListUserTripsResponse
	10, // 22: trip.TripService.UpdateTrip:output_type -> trip.UpdateTripResponse
	12, // 23: trip.TripService.DeleteTrip:output_type -> trip.DeleteTripResponse
	22, // 24: trip.TripService.GenerateInviteLink:output_type -> trip.GenerateInviteLinkResponse
	24, // 25: trip.TripService.JoinTripByToken:output_type -> trip.JoinTripByTokenResponse
	26, // 26: trip.TripService.RemoveParticipant:output_type -> trip.RemoveParticipantResponse
	28, // 27: trip.TripService.LeaveTrip:output_type -> trip.LeaveTripResponse
	30, // 28: trip.TripService.TransferAdmin:output_type -> trip.TransferAdminResponse
	14, // 29: trip.TripService.ProcessMediaGrouping:output_type -> trip.ProcessMediaGroupingResponse
	16, // 30: trip.TripService.ApplyGroupsAndProcess:output_type -> trip.ApplyGroupsAndProcessResponse
	18, // 31: trip.TripService.GetTripReview:output_type -> trip.GetTripReviewResponse
	20, // 32: trip.TripService.FinalizeTrip:output_type -> trip.FinalizeTripResponse
	19, // [19:33] is the sub-list for method output_type
	5,  // [5:19] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_trip_proto_init() }
func file_trip_proto_init() {
	if File_trip_proto != nil {
		return
	}
	file_trip_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_trip_proto_rawDesc), len(file_trip_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_trip_proto_goTypes,
		DependencyIndexes: file_trip_proto_depIdxs,
		MessageInfos:      file_trip_proto_msgTypes,
	}.Build()
	File_trip_proto = out.File
	file_trip_proto_goTypes = nil
	file_trip_proto_depIdxs = nil
}
