apiVersion: v1
kind: Secret
metadata:
  name: trip-service-secret
type: Opaque
stringData:
  db-password: {{ .Values.secret.dbPassword | quote }}
  s3-access-key: {{ .Values.secret.s3AccessKey | quote }}
  s3-secret-key: {{ .Values.secret.s3SecretKey | quote }}
