// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: add_media_sessions.sql

package sqlcdb

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const addMediaSessionCreate = `-- name: AddMediaSessionCreate :one
INSERT INTO add_media_sessions (trip_id, existing_media_ids) VALUES ($1, $2)
RETURNING session_id
`

type AddMediaSessionCreateParams struct {
	TripID           uuid.UUID
	ExistingMediaIds json.RawMessage
}

func (q *Queries) AddMediaSessionCreate(ctx context.Context, arg AddMediaSessionCreateParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, addMediaSessionCreate, arg.TripID, arg.ExistingMediaIds)
	var session_id uuid.UUID
	err := row.Scan(&session_id)
	return session_id, err
}

const addMediaSessionExists = `-- name: AddMediaSessionExists :one
SELECT COUNT(1)::int AS n FROM add_media_sessions WHERE trip_id = $1 AND session_id = $2
`

type AddMediaSessionExistsParams struct {
	TripID    uuid.UUID
	SessionID uuid.UUID
}

func (q *Queries) AddMediaSessionExists(ctx context.Context, arg AddMediaSessionExistsParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, addMediaSessionExists, arg.TripID, arg.SessionID)
	var n int32
	err := row.Scan(&n)
	return n, err
}

const addMediaSessionGet = `-- name: AddMediaSessionGet :one
SELECT trip_id, existing_media_ids FROM add_media_sessions WHERE session_id = $1
`

type AddMediaSessionGetRow struct {
	TripID           uuid.UUID
	ExistingMediaIds json.RawMessage
}

func (q *Queries) AddMediaSessionGet(ctx context.Context, sessionID uuid.UUID) (AddMediaSessionGetRow, error) {
	row := q.db.QueryRowContext(ctx, addMediaSessionGet, sessionID)
	var i AddMediaSessionGetRow
	err := row.Scan(&i.TripID, &i.ExistingMediaIds)
	return i, err
}
