// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: geo_registry.sql

package sqlcdb

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const geoRegistryFindCityByNameAndParent = `-- name: GeoRegistryFindCityByNameAndParent :one
SELECT id FROM geo_registry WHERE name = $1 AND type = 'city' AND parent_id = $2 LIMIT 1
`

type GeoRegistryFindCityByNameAndParentParams struct {
	Name     string
	ParentID sql.NullInt32
}

func (q *Queries) GeoRegistryFindCityByNameAndParent(ctx context.Context, arg GeoRegistryFindCityByNameAndParentParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, geoRegistryFindCityByNameAndParent, arg.Name, arg.ParentID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const geoRegistryFindCityByNameNoParent = `-- name: GeoRegistryFindCityByNameNoParent :one
SELECT id FROM geo_registry WHERE name = $1 AND type = 'city' LIMIT 1
`

func (q *Queries) GeoRegistryFindCityByNameNoParent(ctx context.Context, name string) (int32, error) {
	row := q.db.QueryRowContext(ctx, geoRegistryFindCityByNameNoParent, name)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const geoRegistryFindCountryByName = `-- name: GeoRegistryFindCountryByName :one
SELECT id FROM geo_registry WHERE name = $1 AND type = 'country' LIMIT 1
`

func (q *Queries) GeoRegistryFindCountryByName(ctx context.Context, name string) (int32, error) {
	row := q.db.QueryRowContext(ctx, geoRegistryFindCountryByName, name)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const geoRegistryFindIDsByNamePattern = `-- name: GeoRegistryFindIDsByNamePattern :many
SELECT id FROM geo_registry
WHERE name ILIKE $1 AND (type = 'country' OR type = 'city')
`

func (q *Queries) GeoRegistryFindIDsByNamePattern(ctx context.Context, name string) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, geoRegistryFindIDsByNamePattern, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int32{}
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const geoRegistryGetByIDs = `-- name: GeoRegistryGetByIDs :many
SELECT id, parent_id, name, type FROM geo_registry WHERE id = ANY($1::int[])
`

func (q *Queries) GeoRegistryGetByIDs(ctx context.Context, dollar_1 []int32) ([]GeoRegistry, error) {
	rows, err := q.db.QueryContext(ctx, geoRegistryGetByIDs, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GeoRegistry{}
	for rows.Next() {
		var i GeoRegistry
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.Type,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const geoRegistryMirrorByID = `-- name: GeoRegistryMirrorByID :exec
INSERT INTO geo_registry (id, parent_id, name, type)
VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE SET
 parent_id = EXCLUDED.parent_id,
 name = EXCLUDED.name,
 type = EXCLUDED.type
`

type GeoRegistryMirrorByIDParams struct {
	ID       int32
	ParentID sql.NullInt32
	Name     string
	Type     string
}

// Зеркалит запись master geo_registry из statistics-service в локальную реплику.
// id приходит от master, поэтому мы вставляем фиксированный id и обновляем поля.
func (q *Queries) GeoRegistryMirrorByID(ctx context.Context, arg GeoRegistryMirrorByIDParams) error {
	_, err := q.db.ExecContext(ctx, geoRegistryMirrorByID,
		arg.ID,
		arg.ParentID,
		arg.Name,
		arg.Type,
	)
	return err
}

const tripLocationFilterByLocation = `-- name: TripLocationFilterByLocation :many
SELECT trip_id FROM trip_locations
WHERE location_id = $1 AND trip_id = ANY($2::uuid[])
`

type TripLocationFilterByLocationParams struct {
	LocationID int32
	Column2    []uuid.UUID
}

func (q *Queries) TripLocationFilterByLocation(ctx context.Context, arg TripLocationFilterByLocationParams) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, tripLocationFilterByLocation, arg.LocationID, pq.Array(arg.Column2))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var trip_id uuid.UUID
		if err := rows.Scan(&trip_id); err != nil {
			return nil, err
		}
		items = append(items, trip_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tripLocationInsert = `-- name: TripLocationInsert :exec
INSERT INTO trip_locations (trip_id, location_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type TripLocationInsertParams struct {
	TripID     uuid.UUID
	LocationID int32
}

func (q *Queries) TripLocationInsert(ctx context.Context, arg TripLocationInsertParams) error {
	_, err := q.db.ExecContext(ctx, tripLocationInsert, arg.TripID, arg.LocationID)
	return err
}
