// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: invitation_links.sql

package sqlcdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const invitationLinkByToken = `-- name: InvitationLinkByToken :one
SELECT id, trip_id, token, expires_at, created_at FROM invitation_links WHERE token = $1
`

func (q *Queries) InvitationLinkByToken(ctx context.Context, token string) (InvitationLink, error) {
	row := q.db.QueryRowContext(ctx, invitationLinkByToken, token)
	var i InvitationLink
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const invitationLinkInsert = `-- name: InvitationLinkInsert :exec
INSERT INTO invitation_links (id, trip_id, token, expires_at) VALUES ($1, $2, $3, $4)
`

type InvitationLinkInsertParams struct {
	ID        uuid.UUID
	TripID    uuid.UUID
	Token     string
	ExpiresAt time.Time
}

func (q *Queries) InvitationLinkInsert(ctx context.Context, arg InvitationLinkInsertParams) error {
	_, err := q.db.ExecContext(ctx, invitationLinkInsert,
		arg.ID,
		arg.TripID,
		arg.Token,
		arg.ExpiresAt,
	)
	return err
}
