// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: pin_hidden.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
)

const pinHiddenInsert = `-- name: PinHiddenInsert :exec
INSERT INTO pin_hidden_by_user (pin_id, user_id) VALUES ($1, $2)
ON CONFLICT (pin_id, user_id) DO NOTHING
`

type PinHiddenInsertParams struct {
	PinID  uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) PinHiddenInsert(ctx context.Context, arg PinHiddenInsertParams) error {
	_, err := q.db.ExecContext(ctx, pinHiddenInsert, arg.PinID, arg.UserID)
	return err
}

const pinHiddenIsHidden = `-- name: PinHiddenIsHidden :one
SELECT EXISTS (
 SELECT 1 FROM pin_hidden_by_user WHERE pin_id = $1 AND user_id = $2
)
`

type PinHiddenIsHiddenParams struct {
	PinID  uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) PinHiddenIsHidden(ctx context.Context, arg PinHiddenIsHiddenParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, pinHiddenIsHidden, arg.PinID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const pinHiddenListForUser = `-- name: PinHiddenListForUser :many
SELECT ph.pin_id
FROM pin_hidden_by_user ph
INNER JOIN pins p ON p.id = ph.pin_id
WHERE p.trip_id = $1 AND ph.user_id = $2
`

type PinHiddenListForUserParams struct {
	TripID uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) PinHiddenListForUser(ctx context.Context, arg PinHiddenListForUserParams) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, pinHiddenListForUser, arg.TripID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var pin_id uuid.UUID
		if err := rows.Scan(&pin_id); err != nil {
			return nil, err
		}
		items = append(items, pin_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
