// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: privacy.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
)

const mediaPrivacyListByMedia = `-- name: MediaPrivacyListByMedia :many
SELECT user_id, privacy_level FROM media_privacy WHERE media_id = $1
`

type MediaPrivacyListByMediaRow struct {
	UserID       uuid.UUID
	PrivacyLevel string
}

func (q *Queries) MediaPrivacyListByMedia(ctx context.Context, mediaID uuid.UUID) ([]MediaPrivacyListByMediaRow, error) {
	rows, err := q.db.QueryContext(ctx, mediaPrivacyListByMedia, mediaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaPrivacyListByMediaRow{}
	for rows.Next() {
		var i MediaPrivacyListByMediaRow
		if err := rows.Scan(&i.UserID, &i.PrivacyLevel); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mediaPrivacyUpsert = `-- name: MediaPrivacyUpsert :exec
INSERT INTO media_privacy (media_id, user_id, privacy_level) VALUES ($1, $2, $3)
ON CONFLICT (media_id, user_id) DO UPDATE SET privacy_level = $3
`

type MediaPrivacyUpsertParams struct {
	MediaID      uuid.UUID
	UserID       uuid.UUID
	PrivacyLevel string
}

func (q *Queries) MediaPrivacyUpsert(ctx context.Context, arg MediaPrivacyUpsertParams) error {
	_, err := q.db.ExecContext(ctx, mediaPrivacyUpsert, arg.MediaID, arg.UserID, arg.PrivacyLevel)
	return err
}

const pinPrivacyListByPin = `-- name: PinPrivacyListByPin :many
SELECT user_id, privacy_level FROM pin_privacy WHERE pin_id = $1
`

type PinPrivacyListByPinRow struct {
	UserID       uuid.UUID
	PrivacyLevel string
}

func (q *Queries) PinPrivacyListByPin(ctx context.Context, pinID uuid.UUID) ([]PinPrivacyListByPinRow, error) {
	rows, err := q.db.QueryContext(ctx, pinPrivacyListByPin, pinID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PinPrivacyListByPinRow{}
	for rows.Next() {
		var i PinPrivacyListByPinRow
		if err := rows.Scan(&i.UserID, &i.PrivacyLevel); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pinPrivacyUpsert = `-- name: PinPrivacyUpsert :exec
INSERT INTO pin_privacy (pin_id, user_id, privacy_level) VALUES ($1, $2, $3)
ON CONFLICT (pin_id, user_id) DO UPDATE SET privacy_level = $3
`

type PinPrivacyUpsertParams struct {
	PinID        uuid.UUID
	UserID       uuid.UUID
	PrivacyLevel string
}

func (q *Queries) PinPrivacyUpsert(ctx context.Context, arg PinPrivacyUpsertParams) error {
	_, err := q.db.ExecContext(ctx, pinPrivacyUpsert, arg.PinID, arg.UserID, arg.PrivacyLevel)
	return err
}

const tripPrivacyListByTrip = `-- name: TripPrivacyListByTrip :many
SELECT user_id, privacy_level FROM trip_privacy WHERE trip_id = $1
`

type TripPrivacyListByTripRow struct {
	UserID       uuid.UUID
	PrivacyLevel string
}

func (q *Queries) TripPrivacyListByTrip(ctx context.Context, tripID uuid.UUID) ([]TripPrivacyListByTripRow, error) {
	rows, err := q.db.QueryContext(ctx, tripPrivacyListByTrip, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TripPrivacyListByTripRow{}
	for rows.Next() {
		var i TripPrivacyListByTripRow
		if err := rows.Scan(&i.UserID, &i.PrivacyLevel); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tripPrivacyUpsert = `-- name: TripPrivacyUpsert :exec
INSERT INTO trip_privacy (trip_id, user_id, privacy_level) VALUES ($1, $2, $3)
ON CONFLICT (trip_id, user_id) DO UPDATE SET privacy_level = $3
`

type TripPrivacyUpsertParams struct {
	TripID       uuid.UUID
	UserID       uuid.UUID
	PrivacyLevel string
}

func (q *Queries) TripPrivacyUpsert(ctx context.Context, arg TripPrivacyUpsertParams) error {
	_, err := q.db.ExecContext(ctx, tripPrivacyUpsert, arg.TripID, arg.UserID, arg.PrivacyLevel)
	return err
}
