// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: trip_settings.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const tripSettingsEnsureDefault = `-- name: TripSettingsEnsureDefault :exec
INSERT INTO trip_settings (user_id, trip_id, notifications_enabled) VALUES ($1, $2, true)
ON CONFLICT (user_id, trip_id) DO NOTHING
`

type TripSettingsEnsureDefaultParams struct {
	UserID uuid.UUID
	TripID uuid.UUID
}

func (q *Queries) TripSettingsEnsureDefault(ctx context.Context, arg TripSettingsEnsureDefaultParams) error {
	_, err := q.db.ExecContext(ctx, tripSettingsEnsureDefault, arg.UserID, arg.TripID)
	return err
}

const tripSettingsGetByTripAndUsers = `-- name: TripSettingsGetByTripAndUsers :many
SELECT user_id, notifications_enabled
FROM trip_settings
WHERE trip_id = $1 AND user_id = ANY($2::uuid[])
`

type TripSettingsGetByTripAndUsersParams struct {
	TripID  uuid.UUID
	Column2 []uuid.UUID
}

type TripSettingsGetByTripAndUsersRow struct {
	UserID               uuid.UUID
	NotificationsEnabled bool
}

func (q *Queries) TripSettingsGetByTripAndUsers(ctx context.Context, arg TripSettingsGetByTripAndUsersParams) ([]TripSettingsGetByTripAndUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, tripSettingsGetByTripAndUsers, arg.TripID, pq.Array(arg.Column2))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TripSettingsGetByTripAndUsersRow{}
	for rows.Next() {
		var i TripSettingsGetByTripAndUsersRow
		if err := rows.Scan(&i.UserID, &i.NotificationsEnabled); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tripSettingsUpdateNotifications = `-- name: TripSettingsUpdateNotifications :execrows
UPDATE trip_settings SET notifications_enabled = $1 WHERE trip_id = $2 AND user_id = $3
`

type TripSettingsUpdateNotificationsParams struct {
	NotificationsEnabled bool
	TripID               uuid.UUID
	UserID               uuid.UUID
}

func (q *Queries) TripSettingsUpdateNotifications(ctx context.Context, arg TripSettingsUpdateNotificationsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, tripSettingsUpdateNotifications, arg.NotificationsEnabled, arg.TripID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
