replicaCount: 1

image:
  repository: ghcr.io/dmitry-pr/pinz-api-gateway
  tag: latest
  pullPolicy: IfNotPresent

service:
  name: http
  port: 8080

env:
  apiGatewayPort: "8080"
  authServiceGrpcAddress: "auth-service:50051"
  tripServiceGrpcAddress: "trip-service:50052"
  statisticsServiceGrpcAddress: "statistics-service:50053"
  notificationServiceGrpcAddress: "notification-service:50054"
  redisAddr: "redis:6379"
  swaggerHost: ""
  otelExporterEndpoint: "otel-collector.default.svc.cluster.local:4317"
  otelServiceName: "api-gateway-service"
  otelTracesSampler: "parentbased_traceidratio"
  otelTracesSamplerArg: "1.0"

resources:
  requests:
    cpu: "50m"
    memory: "64Mi"
  limits:
    cpu: "200m"
    memory: "128Mi"

pdb:
  enabled: false
  minAvailable: 1

dockerConfig:
  auths:
    ghcr.io:
      username: "{{ .Values.github.actor }}"
      password: "{{ .Values.github.token }}"
