apiVersion: v1
kind: Secret
metadata:
  name: notification-service-secret
type: Opaque
stringData:
  db-password: {{ .Values.secret.dbPassword | quote }}
  apns-key-base64: {{ .Values.secret.apnsKeyBase64 | quote }}
  smtp-username: {{ .Values.secret.smtpUsername | quote }}
  smtp-password: {{ .Values.secret.smtpPassword | quote }}
