replicaCount: 1

image:
  repository: ghcr.io/dmitry-pr/pinz-statistics-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  name: grpc
  port: 50053

env:
  dbHost: db-stats
  dbPort: "5434"
  dbUser: pinz_user
  dbName: pinz_stats
  redisAddr: redis:6379
  grpcPort: ":50053"
  otelExporterEndpoint: "otel-collector.default.svc.cluster.local:4317"
  otelServiceName: "statistics-service"
  otelTracesSampler: "parentbased_always_on"
  otelTracesSamplerArg: "1.0"
  geocodingBaseUrl: "https://api.bigdatacloud.net/data/reverse-geocode-client"

secret:
  dbPassword: "REPLACE_IN_PRODUCTION"
  geocodingApiKey: ""

resources:
  requests:
    cpu: "50m"
    memory: "48Mi"
  limits:
    cpu: "200m"
    memory: "96Mi"

pdb:
  enabled: false
  minAvailable: 1

dockerConfig:
  auths:
    ghcr.io:
      username: "{{ .Values.github.actor }}"
      password: "{{ .Values.github.token }}"
