name: CI auth-service

on:
  push:
    branches: [main, develop, 'PINZ-*']
    paths:
      - 'Backend/auth-service/**'
      - 'Backend/pkg/**'
      - 'Backend/proto/**'
      - '.github/workflows/ci-auth-service.yaml'
      - '.github/workflows/ci-reusable.yaml'
  pull_request:
    branches: [main, develop, 'PINZ-*']
    paths:
      - 'Backend/auth-service/**'
      - 'Backend/pkg/**'
      - 'Backend/proto/**'
      - '.github/workflows/ci-auth-service.yaml'
      - '.github/workflows/ci-reusable.yaml'

jobs:
  ci:
    uses: ./.github/workflows/ci-reusable.yaml
    with:
      service: auth-service
    secrets: inherit
